//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.General.Control {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.General.Control.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即重连.
        /// </summary>
        public static string C_Reconnect {
            get {
                return ResourceManager.GetString("C_Reconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点通道地址无效，未保存.
        /// </summary>
        public static string M_EndpointRejected {
            get {
                return ResourceManager.GetString("M_EndpointRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该组下没有这个节点，请先在控制台注册.
        /// </summary>
        public static string M_Detail_NodeNotFound {
            get {
                return ResourceManager.GetString("M_Detail_NodeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 组不存在，或当前账号不是该组成员.
        /// </summary>
        public static string M_Detail_GroupNotFound {
            get {
                return ResourceManager.GetString("M_Detail_GroupNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请求格式错误，这是客户端问题.
        /// </summary>
        public static string M_Detail_InvalidRequest {
            get {
                return ResourceManager.GetString("M_Detail_InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 还没有填写所属组 ID.
        /// </summary>
        public static string M_Detail_NotConfigured {
            get {
                return ResourceManager.GetString("M_Detail_NotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 尚未接入自建集控，请在上面的「接入自建集控」卡片里填写控制台签发的接入码.
        /// </summary>
        /// <summary>
        ///   Looks up a localized string similar to 服务端已拒绝本机接入令牌，请在上面的「接入自建集控」卡片里重新接入.
        /// </summary>
        public static string M_Detail_EnrollmentRejected {
            get {
                return ResourceManager.GetString("M_Detail_EnrollmentRejected", resourceCulture);
            }
        }

        public static string M_Detail_NotEnrolled {
            get {
                return ResourceManager.GetString("M_Detail_NotEnrolled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 尚未登录 SECTL 账号.
        /// </summary>
        public static string M_Detail_NotSignedIn {
            get {
                return ResourceManager.GetString("M_Detail_NotSignedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 凭据无效，请重新登录.
        /// </summary>
        public static string M_Detail_Unauthorized {
            get {
                return ResourceManager.GetString("M_Detail_Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点通道地址无效.
        /// </summary>
        public static string M_Detail_EndpointInvalid {
            get {
                return ResourceManager.GetString("M_Detail_EndpointInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已停止重试.
        /// </summary>
        public static string M_Status_Blocked {
            get {
                return ResourceManager.GetString("M_Status_Blocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已连接.
        /// </summary>
        public static string M_Status_Connected {
            get {
                return ResourceManager.GetString("M_Status_Connected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 连接中.
        /// </summary>
        public static string M_Status_Connecting {
            get {
                return ResourceManager.GetString("M_Status_Connecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已关闭.
        /// </summary>
        public static string M_Status_Disabled {
            get {
                return ResourceManager.GetString("M_Status_Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待登录或填写组 ID.
        /// </summary>
        public static string M_Status_Idle {
            get {
                return ResourceManager.GetString("M_Status_Idle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 需要重新接入.
        /// </summary>
        public static string M_Status_ReenrollRequired {
            get {
                return ResourceManager.GetString("M_Status_ReenrollRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待重连.
        /// </summary>
        public static string M_Status_WaitingToRetry {
            get {
                return ResourceManager.GetString("M_Status_WaitingToRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集控.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 远程控制.
        /// </summary>
        public static string S_RemoteControl {
            get {
                return ResourceManager.GetString("S_RemoteControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示名称.
        /// </summary>
        public static string S_RemoteControl_DisplayName {
            get {
                return ResourceManager.GetString("S_RemoteControl_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控制台节点列表里显示的名字；留空则上报本机主机名.
        /// </summary>
        public static string S_RemoteControl_DisplayName_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_DisplayName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取锁定.
        /// </summary>
        public static string S_RemoteControl_DrawLocked {
            get {
                return ResourceManager.GetString("S_RemoteControl_DrawLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 由控制台设置；锁定后本机不再允许抽取.
        /// </summary>
        public static string S_RemoteControl_DrawLocked_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_DrawLocked_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在主界面显示远程抽取页.
        /// </summary>
        public static string S_RemoteDrawPage {
            get {
                return ResourceManager.GetString("S_RemoteDrawPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开后主界面侧栏出现『远程抽取』页，可向本组其他设备下发抽取；使用前需要登录账号，服务端仍按组成员角色判定权限；关闭后立刻隐藏.
        /// </summary>
        public static string S_RemoteDrawPage_D {
            get {
                return ResourceManager.GetString("S_RemoteDrawPage_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 允许被远程控制.
        /// </summary>
        public static string S_RemoteControl_Enabled {
            get {
                return ResourceManager.GetString("S_RemoteControl_Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 这是本机自己的开关，关闭后无论服务端下发什么命令都不会执行.
        /// </summary>
        public static string S_RemoteControl_Enabled_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_Enabled_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 所属组 ID.
        /// </summary>
        public static string S_RemoteControl_GroupId {
            get {
                return ResourceManager.GetString("S_RemoteControl_GroupId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 由控制台建组后提供；节点必须先在该组注册，否则连接会被拒绝.
        /// </summary>
        public static string S_RemoteControl_GroupId_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_GroupId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点 ID.
        /// </summary>
        public static string S_RemoteControl_NodeId {
            get {
                return ResourceManager.GetString("S_RemoteControl_NodeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 安装时生成并长期保持不变，注册节点时把它填进控制台.
        /// </summary>
        public static string S_RemoteControl_NodeId_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_NodeId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点通道地址.
        /// </summary>
        public static string S_RemoteControl_ServerUrl {
            get {
                return ResourceManager.GetString("S_RemoteControl_ServerUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认使用线上节点通道；仅回环地址允许明文 ws 连接.
        /// </summary>
        public static string S_RemoteControl_ServerUrl_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_ServerUrl_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 连接状态.
        /// </summary>
        public static string S_RemoteControl_Status {
            get {
                return ResourceManager.GetString("S_RemoteControl_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 断线后按退避自动重连；重试也没有意义的失败会停在这里等待修正.
        /// </summary>
        public static string S_RemoteControl_Status_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_Status_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集控平台.
        /// </summary>
        public static string S_ControlPlatform {
            get {
                return ResourceManager.GetString("S_ControlPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点信息.
        /// </summary>
        public static string S_NodeInfo {
            get {
                return ResourceManager.GetString("S_NodeInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 连接与状态.
        /// </summary>
        public static string S_ConnectionStatus {
            get {
                return ResourceManager.GetString("S_ConnectionStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 高级连接设置.
        /// </summary>
        public static string S_AdvancedConnections {
            get {
                return ResourceManager.GetString("S_AdvancedConnections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控制面地址.
        /// </summary>
        public static string S_ControlPlaneEndpoint {
            get {
                return ResourceManager.GetString("S_ControlPlaneEndpoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控制台访问集控平台所用的基址，留空即回到线上默认地址.
        /// </summary>
        public static string S_ControlPlaneEndpoint_D {
            get {
                return ResourceManager.GetString("S_ControlPlaneEndpoint_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复默认.
        /// </summary>
        public static string C_RestoreDefaultEndpoint {
            get {
                return ResourceManager.GetString("C_RestoreDefaultEndpoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控制面地址无效，未保存：必须使用 https，只有回环地址允许明文 http.
        /// </summary>
        public static string M_ControlPlaneEndpointRejected {
            get {
                return ResourceManager.GetString("M_ControlPlaneEndpointRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集控平台.
        /// </summary>
        public static string S_OpenControlPlane {
            get {
                return ResourceManager.GetString("S_OpenControlPlane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在浏览器中打开集控平台网页控制台，管理加入本组的设备.
        /// </summary>
        public static string S_OpenControlPlane_D {
            get {
                return ResourceManager.GetString("S_OpenControlPlane_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开SecRandom集控平台.
        /// </summary>
        public static string C_OpenControlPlane_Official {
            get {
                return ResourceManager.GetString("C_OpenControlPlane_Official", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开第三方托管集控平台.
        /// </summary>
        public static string C_OpenControlPlane_ThirdParty {
            get {
                return ResourceManager.GetString("C_OpenControlPlane_ThirdParty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 接入自建集控.
        /// </summary>
        public static string S_NodeEnrollment {
            get {
                return ResourceManager.GetString("S_NodeEnrollment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用控制台签发的接入码把本机接入自建集控.
        /// </summary>
        public static string S_NodeEnrollment_D {
            get {
                return ResourceManager.GetString("S_NodeEnrollment_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 接入码.
        /// </summary>
        public static string S_NodeEnrollment_Code {
            get {
                return ResourceManager.GetString("S_NodeEnrollment_Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 粘贴控制台签发的接入码.
        /// </summary>
        public static string S_NodeEnrollment_Code_Ph {
            get {
                return ResourceManager.GetString("S_NodeEnrollment_Code_Ph", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 接入.
        /// </summary>
        public static string C_Enroll {
            get {
                return ResourceManager.GetString("C_Enroll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 清除接入.
        /// </summary>
        public static string C_ClearEnrollment {
            get {
                return ResourceManager.GetString("C_ClearEnrollment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 未接入.
        /// </summary>
        public static string M_Enroll_None {
            get {
                return ResourceManager.GetString("M_Enroll_None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已接入：{0}.
        /// </summary>
        public static string M_Enroll_Active {
            get {
                return ResourceManager.GetString("M_Enroll_Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 接入已过期.
        /// </summary>
        public static string M_Enroll_Expired {
            get {
                return ResourceManager.GetString("M_Enroll_Expired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 需要重新接入.
        /// </summary>
        public static string M_Enroll_Unreadable {
            get {
                return ResourceManager.GetString("M_Enroll_Unreadable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点令牌加密保存在本机.
        /// </summary>
        public static string M_Enroll_TokenHint {
            get {
                return ResourceManager.GetString("M_Enroll_TokenHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 接入失败：{0}.
        /// </summary>
        public static string M_Enroll_Detail {
            get {
                return ResourceManager.GetString("M_Enroll_Detail", resourceCulture);
            }
        }
    }
}
