//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.General.Control {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.General.Control.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即重连.
        /// </summary>
        public static string C_Reconnect {
            get {
                return ResourceManager.GetString("C_Reconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点通道地址无效，未保存.
        /// </summary>
        public static string M_EndpointRejected {
            get {
                return ResourceManager.GetString("M_EndpointRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该组下没有这个节点，请先在控制台注册.
        /// </summary>
        public static string M_Detail_NodeNotFound {
            get {
                return ResourceManager.GetString("M_Detail_NodeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 组不存在，或当前账号不是该组成员.
        /// </summary>
        public static string M_Detail_GroupNotFound {
            get {
                return ResourceManager.GetString("M_Detail_GroupNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请求格式错误，这是客户端问题.
        /// </summary>
        public static string M_Detail_InvalidRequest {
            get {
                return ResourceManager.GetString("M_Detail_InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 还没有填写所属组 ID.
        /// </summary>
        public static string M_Detail_NotConfigured {
            get {
                return ResourceManager.GetString("M_Detail_NotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 尚未登录 SECTL 账号.
        /// </summary>
        public static string M_Detail_NotSignedIn {
            get {
                return ResourceManager.GetString("M_Detail_NotSignedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 凭据无效，请重新登录.
        /// </summary>
        public static string M_Detail_Unauthorized {
            get {
                return ResourceManager.GetString("M_Detail_Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点通道地址无效.
        /// </summary>
        public static string M_Detail_EndpointInvalid {
            get {
                return ResourceManager.GetString("M_Detail_EndpointInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已停止重试.
        /// </summary>
        public static string M_Status_Blocked {
            get {
                return ResourceManager.GetString("M_Status_Blocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已连接.
        /// </summary>
        public static string M_Status_Connected {
            get {
                return ResourceManager.GetString("M_Status_Connected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 连接中.
        /// </summary>
        public static string M_Status_Connecting {
            get {
                return ResourceManager.GetString("M_Status_Connecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已关闭.
        /// </summary>
        public static string M_Status_Disabled {
            get {
                return ResourceManager.GetString("M_Status_Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待登录或填写组 ID.
        /// </summary>
        public static string M_Status_Idle {
            get {
                return ResourceManager.GetString("M_Status_Idle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 等待重连.
        /// </summary>
        public static string M_Status_WaitingToRetry {
            get {
                return ResourceManager.GetString("M_Status_WaitingToRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 集控.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 远程控制.
        /// </summary>
        public static string S_RemoteControl {
            get {
                return ResourceManager.GetString("S_RemoteControl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 显示名称.
        /// </summary>
        public static string S_RemoteControl_DisplayName {
            get {
                return ResourceManager.GetString("S_RemoteControl_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 控制台节点列表里显示的名字；留空则上报本机主机名.
        /// </summary>
        public static string S_RemoteControl_DisplayName_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_DisplayName_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取锁定.
        /// </summary>
        public static string S_RemoteControl_DrawLocked {
            get {
                return ResourceManager.GetString("S_RemoteControl_DrawLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 由控制台设置；锁定后本机不再允许抽取.
        /// </summary>
        public static string S_RemoteControl_DrawLocked_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_DrawLocked_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 允许被远程控制.
        /// </summary>
        public static string S_RemoteControl_Enabled {
            get {
                return ResourceManager.GetString("S_RemoteControl_Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 这是本机自己的开关，关闭后无论服务端下发什么命令都不会执行.
        /// </summary>
        public static string S_RemoteControl_Enabled_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_Enabled_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 所属组 ID.
        /// </summary>
        public static string S_RemoteControl_GroupId {
            get {
                return ResourceManager.GetString("S_RemoteControl_GroupId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 由控制台建组后提供；节点必须先在该组注册，否则连接会被拒绝.
        /// </summary>
        public static string S_RemoteControl_GroupId_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_GroupId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点 ID.
        /// </summary>
        public static string S_RemoteControl_NodeId {
            get {
                return ResourceManager.GetString("S_RemoteControl_NodeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 安装时生成并长期保持不变，注册节点时把它填进控制台.
        /// </summary>
        public static string S_RemoteControl_NodeId_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_NodeId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 节点通道地址.
        /// </summary>
        public static string S_RemoteControl_ServerUrl {
            get {
                return ResourceManager.GetString("S_RemoteControl_ServerUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认使用线上节点通道；仅回环地址允许明文 ws 连接.
        /// </summary>
        public static string S_RemoteControl_ServerUrl_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_ServerUrl_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 连接状态.
        /// </summary>
        public static string S_RemoteControl_Status {
            get {
                return ResourceManager.GetString("S_RemoteControl_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 断线后按退避自动重连；重试也没有意义的失败会停在这里等待修正.
        /// </summary>
        public static string S_RemoteControl_Status_D {
            get {
                return ResourceManager.GetString("S_RemoteControl_Status_D", resourceCulture);
            }
        }
    }
}
