//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsView.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多选项....
        /// </summary>
        public static string C_MoreOptions {
            get {
                return ResourceManager.GetString("C_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出所有数据.
        /// </summary>
        public static string C_MoreOptions_ExportAllData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出软件时导出全部数据和设置.
        /// </summary>
        public static string C_MoreOptions_ExportAllData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportAllData_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出诊断数据.
        /// </summary>
        public static string C_MoreOptions_ExportDiagnosticData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportDiagnosticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出软件时导出诊断信息，用于排查问题.
        /// </summary>
        public static string C_MoreOptions_ExportDiagnosticData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportDiagnosticData_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出设置.
        /// </summary>
        public static string C_MoreOptions_ExportSettings {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将当前设置导出为配置文件，用于备份和迁移.
        /// </summary>
        public static string C_MoreOptions_ExportSettings_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportSettings_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入所有数据.
        /// </summary>
        public static string C_MoreOptions_ImportAllData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动软件时从备份文件恢复全部数据.
        /// </summary>
        public static string C_MoreOptions_ImportAllData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportAllData_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入设置.
        /// </summary>
        public static string C_MoreOptions_ImportSettings {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从配置文件导入设置，覆盖当前配置信息.
        /// </summary>
        public static string C_MoreOptions_ImportSettings_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportSettings_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看日志.
        /// </summary>
        public static string C_MoreOptions_LogViewer {
            get {
                return ResourceManager.GetString("C_MoreOptions_LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看和管理程序日志文件.
        /// </summary>
        public static string C_MoreOptions_LogViewer_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_LogViewer_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索设置....
        /// </summary>
        public static string C_SearchBox_Watermark {
            get {
                return ResourceManager.GetString("C_SearchBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要重启.
        /// </summary>
        public static string M_NeedsRestarting {
            get {
                return ResourceManager.GetString("M_NeedsRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string M_NeedsRestarting_Close {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分设置需要重启以应用更改。.
        /// </summary>
        public static string M_NeedsRestarting_D {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启.
        /// </summary>
        public static string M_NeedsRestarting_Primary {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分设置需要重启才能生效，点击以重启应用。.
        /// </summary>
        public static string M_NeedsRestarting_Tooltip {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面 {0} 未找到.
        /// </summary>
        public static string M_PageNotFound {
            get {
                return ResourceManager.GetString("M_PageNotFound", resourceCulture);
            }
        }
    }
}
