//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsView {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SecRandom.Langs.SettingsView.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string M_NeedsRestarting {
            get {
                return ResourceManager.GetString("M_NeedsRestarting", resourceCulture);
            }
        }
        
        public static string M_NeedsRestarting_D {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_D", resourceCulture);
            }
        }
        
        public static string M_NeedsRestarting_Primary {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Primary", resourceCulture);
            }
        }
        
        public static string M_NeedsRestarting_Close {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Close", resourceCulture);
            }
        }
        
        public static string M_NeedsRestarting_Tooltip {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Tooltip", resourceCulture);
            }
        }
        
        public static string C_SearchBox_Watermark {
            get {
                return ResourceManager.GetString("C_SearchBox_Watermark", resourceCulture);
            }
        }
        
        public static string C_MoreOptions {
            get {
                return ResourceManager.GetString("C_MoreOptions", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_LogViewer {
            get {
                return ResourceManager.GetString("C_MoreOptions_LogViewer", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_LogViewer_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_LogViewer_D", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ExportDiagnosticData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportDiagnosticData", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ExportDiagnosticData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportDiagnosticData_D", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ExportSettings {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportSettings", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ExportSettings_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportSettings_D", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ImportSettings {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportSettings", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ImportSettings_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportSettings_D", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ExportAllData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportAllData", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ExportAllData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportAllData_D", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ImportAllData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportAllData", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_ImportAllData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportAllData_D", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_OpenLogDirectory {
            get {
                return ResourceManager.GetString("C_MoreOptions_OpenLogDirectory", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_OpenDataDirectory {
            get {
                return ResourceManager.GetString("C_MoreOptions_OpenDataDirectory", resourceCulture);
            }
        }
        
        public static string C_MoreOptions_OpenAppDirectory {
            get {
                return ResourceManager.GetString("C_MoreOptions_OpenAppDirectory", resourceCulture);
            }
        }
        
        public static string C_ExportSettingsFileTitle {
            get {
                return ResourceManager.GetString("C_ExportSettingsFileTitle", resourceCulture);
            }
        }
        
        public static string C_ExportDiagnosticDataFileTitle {
            get {
                return ResourceManager.GetString("C_ExportDiagnosticDataFileTitle", resourceCulture);
            }
        }
        
        public static string C_ImportSettingsFileTitle {
            get {
                return ResourceManager.GetString("C_ImportSettingsFileTitle", resourceCulture);
            }
        }
        
        public static string C_ExportAllDataFileTitle {
            get {
                return ResourceManager.GetString("C_ExportAllDataFileTitle", resourceCulture);
            }
        }
        
        public static string C_ImportAllDataFileTitle {
            get {
                return ResourceManager.GetString("C_ImportAllDataFileTitle", resourceCulture);
            }
        }
        
        public static string C_JsonFileType {
            get {
                return ResourceManager.GetString("C_JsonFileType", resourceCulture);
            }
        }
        
        public static string C_ZipFileType {
            get {
                return ResourceManager.GetString("C_ZipFileType", resourceCulture);
            }
        }
        
        public static string C_Import {
            get {
                return ResourceManager.GetString("C_Import", resourceCulture);
            }
        }
        
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }
        
        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }
        
        public static string C_DiagnosticStandard {
            get {
                return ResourceManager.GetString("C_DiagnosticStandard", resourceCulture);
            }
        }
        
        public static string C_DiagnosticExtended {
            get {
                return ResourceManager.GetString("C_DiagnosticExtended", resourceCulture);
            }
        }
        
        public static string M_DiagnosticExportTitle {
            get {
                return ResourceManager.GetString("M_DiagnosticExportTitle", resourceCulture);
            }
        }
        
        public static string M_DiagnosticExportContent {
            get {
                return ResourceManager.GetString("M_DiagnosticExportContent", resourceCulture);
            }
        }
        
        public static string M_ImportTitle {
            get {
                return ResourceManager.GetString("M_ImportTitle", resourceCulture);
            }
        }
        
        public static string M_ImportSettingsContent {
            get {
                return ResourceManager.GetString("M_ImportSettingsContent", resourceCulture);
            }
        }
        
        public static string M_ImportAllDataContent {
            get {
                return ResourceManager.GetString("M_ImportAllDataContent", resourceCulture);
            }
        }
        
        public static string M_ImportUnsupportedTitle {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedTitle", resourceCulture);
            }
        }
        
        public static string M_ImportUnsupportedContent {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedContent", resourceCulture);
            }
        }
        
        public static string M_ImportUnsupportedUnknownVersion {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedUnknownVersion", resourceCulture);
            }
        }
        
        public static string M_ImportUnsupportedVersion {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedVersion", resourceCulture);
            }
        }
        
        public static string M_ExportSuccess {
            get {
                return ResourceManager.GetString("M_ExportSuccess", resourceCulture);
            }
        }
        
        public static string M_ImportSuccess {
            get {
                return ResourceManager.GetString("M_ImportSuccess", resourceCulture);
            }
        }
        
        public static string M_ExportFailed {
            get {
                return ResourceManager.GetString("M_ExportFailed", resourceCulture);
            }
        }
        
        public static string M_ImportFailed {
            get {
                return ResourceManager.GetString("M_ImportFailed", resourceCulture);
            }
        }
        
        public static string M_OpenDirectoryFailed {
            get {
                return ResourceManager.GetString("M_OpenDirectoryFailed", resourceCulture);
            }
        }
        
        public static string M_PageNotFound {
            get {
                return ResourceManager.GetString("M_PageNotFound", resourceCulture);
            }
        }
        
        public static string M_NavigateFailed {
            get {
                return ResourceManager.GetString("M_NavigateFailed", resourceCulture);
            }
        }
    }
}
