//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.ProfileSettings {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.ProfileSettings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Command_Help {
            get {
                return ResourceManager.GetString("Command_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开“编辑档案&quot;的文档.
        /// </summary>
        public static string Command_Help_D {
            get {
                return ResourceManager.GetString("Command_Help_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 保存当前全部档案.
        /// </summary>
        public static string Command_Save_D {
            get {
                return ResourceManager.GetString("Command_Save_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已保存。.
        /// </summary>
        public static string Message_SavedProfile {
            get {
                return ResourceManager.GetString("Message_SavedProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string Page_History {
            get {
                return ResourceManager.GetString("Page_History", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 奖项.
        /// </summary>
        public static string Page_Prizes {
            get {
                return ResourceManager.GetString("Page_Prizes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 学生.
        /// </summary>
        public static string Page_Students {
            get {
                return ResourceManager.GetString("Page_Students", resourceCulture);
            }
        }
    }
}
