//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一个易用的点名/抽奖软件，专为教育场景设计，让课堂点名更高效透明.
        /// </summary>
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本项目基于 GNU General Public License v3.0 获得许可。.
        /// </summary>
        public static string App_License {
            get {
                return ResourceManager.GetString("App_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内幕设置.
        /// </summary>
        public static string AttachedSettings_BehindScene {
            get {
                return ResourceManager.GetString("AttachedSettings_BehindScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (等待编写).
        /// </summary>
        public static string C_ToBeWritten {
            get {
                return ResourceManager.GetString("C_ToBeWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸抽取.
        /// </summary>
        public static string Feat_FaceDraw {
            get {
                return ResourceManager.GetString("Feat_FaceDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string Feat_History {
            get {
                return ResourceManager.GetString("Feat_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖.
        /// </summary>
        public static string Feat_Lottery {
            get {
                return ResourceManager.GetString("Feat_Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽.
        /// </summary>
        public static string Feat_QuickDraw {
            get {
                return ResourceManager.GetString("Feat_QuickDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名.
        /// </summary>
        public static string Feat_RollCall {
            get {
                return ResourceManager.GetString("Feat_RollCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Feat_Settings {
            get {
                return ResourceManager.GetString("Feat_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计时器.
        /// </summary>
        public static string Feat_Timer {
            get {
                return ResourceManager.GetString("Feat_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出程序.
        /// </summary>
        public static string Menu_ExitProgram {
            get {
                return ResourceManager.GetString("Menu_ExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开主窗口.
        /// </summary>
        public static string Menu_OpenMainWindow {
            get {
                return ResourceManager.GetString("Menu_OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑档案.
        /// </summary>
        public static string Menu_OpenProfileSettings {
            get {
                return ResourceManager.GetString("Menu_OpenProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开设置.
        /// </summary>
        public static string Menu_OpenSettings {
            get {
                return ResourceManager.GetString("Menu_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于 SecRandom.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string Settings_Basic {
            get {
                return ResourceManager.GetString("Settings_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取设置.
        /// </summary>
        public static string Settings_Draw {
            get {
                return ResourceManager.GetString("Settings_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮窗管理.
        /// </summary>
        public static string Settings_FloatingWindow {
            get {
                return ResourceManager.GetString("Settings_FloatingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联动设置.
        /// </summary>
        public static string Settings_Linkage {
            get {
                return ResourceManager.GetString("Settings_Linkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖通知设置.
        /// </summary>
        public static string Settings_LotteryNotification {
            get {
                return ResourceManager.GetString("Settings_LotteryNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知设置.
        /// </summary>
        public static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闪抽通知设置.
        /// </summary>
        public static string Settings_QuickDrawNotification {
            get {
                return ResourceManager.GetString("Settings_QuickDrawNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名通知设置.
        /// </summary>
        public static string Settings_RollCallNotification {
            get {
                return ResourceManager.GetString("Settings_RollCallNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名单管理.
        /// </summary>
        public static string Settings_RosterManagement {
            get {
                return ResourceManager.GetString("Settings_RosterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全设置.
        /// </summary>
        public static string Settings_Security {
            get {
                return ResourceManager.GetString("Settings_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题管理.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新设置.
        /// </summary>
        public static string Settings_Update {
            get {
                return ResourceManager.GetString("Settings_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语音设置.
        /// </summary>
        public static string Settings_Voice {
            get {
                return ResourceManager.GetString("Settings_Voice", resourceCulture);
            }
        }
    }
}
