; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#ifndef MyAppName
#define MyAppName "SecRandom"
#endif
#ifndef MyAppVersion
#define MyAppVersion "APP_VERSION"
#endif
#define MyAppPublisher "SECTL Studio"
#define MyAppExeName "SecRandom.Desktop.exe"
#define MyAppURL "https://secrandom.sectl.cn/"
#ifndef MyAppOutDir
#define MyAppOutDir "APP_OUTDIR"
#endif
#ifndef EnableUiAccess
#define EnableUiAccess 0
#endif
#ifndef BuildArch
#define BuildArch "x64"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{841EEEA5-9A56-4DF5-9E75-27EEA063EF1F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppSupportURL={#MyAppURL}
#if EnableUiAccess == 1
DefaultDirName={autopf}\SecRandom
#else
DefaultDirName={localappdata}\SecRandom
#endif
UninstallDisplayIcon={app}\{#MyAppExeName}
#if BuildArch == "x86"
ArchitecturesAllowed=x86compatible
#else
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
#endif
DisableProgramGroupPage=yes
; LicenseFile=E:\Projects\Avalonia\SecRandom\LICENSE
#if EnableUiAccess == 1
; UIAccess is granted only to signed binaries installed under Program Files.
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=none
#else
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
#endif
OutputDir=SetupOutput
OutputBaseFilename=SecRandom-Setup
SetupIconFile=SecRandom\Assets\AppLogo.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppOutDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppOutDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

