//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.More {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.More.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按下快捷键.
        /// </summary>
        public static string C_ShortcutCapture {
            get {
                return ResourceManager.GetString("C_ShortcutCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空快捷键.
        /// </summary>
        public static string C_ShortcutClear {
            get {
                return ResourceManager.GetString("C_ShortcutClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用抽奖.
        /// </summary>
        public static string S_LotteryEnabled {
            get {
                return ResourceManager.GetString("S_LotteryEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭后隐藏抽奖入口，并拒绝抽奖快捷键和外部指令。.
        /// </summary>
        public static string S_LotteryEnabled_D {
            get {
                return ResourceManager.GetString("S_LotteryEnabled_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冲突.
        /// </summary>
        public static string C_ShortcutConflict {
            get {
                return ResourceManager.GetString("C_ShortcutConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例如 Ctrl+Alt+L.
        /// </summary>
        public static string C_ShortcutExampleLottery {
            get {
                return ResourceManager.GetString("C_ShortcutExampleLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例如 Ctrl+Alt+Q.
        /// </summary>
        public static string C_ShortcutExampleQuickDraw {
            get {
                return ResourceManager.GetString("C_ShortcutExampleQuickDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例如 Ctrl+Alt+R.
        /// </summary>
        public static string C_ShortcutExampleRollCall {
            get {
                return ResourceManager.GetString("C_ShortcutExampleRollCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该快捷键已分配给其他操作。.
        /// </summary>
        public static string M_ShortcutDuplicated {
            get {
                return ResourceManager.GetString("M_ShortcutDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左侧.
        /// </summary>
        public static string O_Left {
            get {
                return ResourceManager.GetString("O_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右侧.
        /// </summary>
        public static string O_Right {
            get {
                return ResourceManager.GetString("O_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多设置.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖页面控件.
        /// </summary>
        public static string S_LotteryControls {
            get {
                return ResourceManager.GetString("S_LotteryControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制抽奖页侧边控制面板中的控件显示。.
        /// </summary>
        public static string S_LotteryControls_D {
            get {
                return ResourceManager.GetString("S_LotteryControls_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别选择.
        /// </summary>
        public static string S_LotteryGenderSelector {
            get {
                return ResourceManager.GetString("S_LotteryGenderSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖池选择.
        /// </summary>
        public static string S_LotteryListSelector {
            get {
                return ResourceManager.GetString("S_LotteryListSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖控制面板位置.
        /// </summary>
        public static string S_LotteryPanelPosition {
            get {
                return ResourceManager.GetString("S_LotteryPanelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽奖页控制面板显示在主内容左侧或右侧。.
        /// </summary>
        public static string S_LotteryPanelPosition_D {
            get {
                return ResourceManager.GetString("S_LotteryPanelPosition_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量调节.
        /// </summary>
        public static string S_LotteryQuantityControl {
            get {
                return ResourceManager.GetString("S_LotteryQuantityControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖数统计.
        /// </summary>
        public static string S_LotteryQuantityLabel {
            get {
                return ResourceManager.GetString("S_LotteryQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 范围选择.
        /// </summary>
        public static string S_LotteryRangeSelector {
            get {
                return ResourceManager.GetString("S_LotteryRangeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余名单按钮.
        /// </summary>
        public static string S_LotteryRemainingButton {
            get {
                return ResourceManager.GetString("S_LotteryRemainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置按钮.
        /// </summary>
        public static string S_LotteryResetButton {
            get {
                return ResourceManager.GetString("S_LotteryResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始按钮.
        /// </summary>
        public static string S_LotteryStartButton {
            get {
                return ResourceManager.GetString("S_LotteryStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生名单选择.
        /// </summary>
        public static string S_LotteryStudentListSelector {
            get {
                return ResourceManager.GetString("S_LotteryStudentListSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面管理.
        /// </summary>
        public static string S_PageManagement {
            get {
                return ResourceManager.GetString("S_PageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名页面控件.
        /// </summary>
        public static string S_RollCallControls {
            get {
                return ResourceManager.GetString("S_RollCallControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制点名页侧边控制面板中的控件显示。.
        /// </summary>
        public static string S_RollCallControls_D {
            get {
                return ResourceManager.GetString("S_RollCallControls_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别选择.
        /// </summary>
        public static string S_RollCallGenderSelector {
            get {
                return ResourceManager.GetString("S_RollCallGenderSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名单选择.
        /// </summary>
        public static string S_RollCallListSelector {
            get {
                return ResourceManager.GetString("S_RollCallListSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名控制面板位置.
        /// </summary>
        public static string S_RollCallPanelPosition {
            get {
                return ResourceManager.GetString("S_RollCallPanelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置点名页控制面板显示在主内容左侧或右侧。.
        /// </summary>
        public static string S_RollCallPanelPosition_D {
            get {
                return ResourceManager.GetString("S_RollCallPanelPosition_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人数调节.
        /// </summary>
        public static string S_RollCallQuantityControl {
            get {
                return ResourceManager.GetString("S_RollCallQuantityControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人数统计.
        /// </summary>
        public static string S_RollCallQuantityLabel {
            get {
                return ResourceManager.GetString("S_RollCallQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 范围选择.
        /// </summary>
        public static string S_RollCallRangeSelector {
            get {
                return ResourceManager.GetString("S_RollCallRangeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余名单按钮.
        /// </summary>
        public static string S_RollCallRemainingButton {
            get {
                return ResourceManager.GetString("S_RollCallRemainingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置按钮.
        /// </summary>
        public static string S_RollCallResetButton {
            get {
                return ResourceManager.GetString("S_RollCallResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始按钮.
        /// </summary>
        public static string S_RollCallStartButton {
            get {
                return ResourceManager.GetString("S_RollCallStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快捷键.
        /// </summary>
        public static string S_Shortcut {
            get {
                return ResourceManager.GetString("S_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展开后按下所需组合键；Esc 取消输入。.
        /// </summary>
        public static string S_Shortcut_D {
            get {
                return ResourceManager.GetString("S_Shortcut_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 减少抽奖数量.
        /// </summary>
        public static string S_Shortcut_DecreaseLotteryCount {
            get {
                return ResourceManager.GetString("S_Shortcut_DecreaseLotteryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 减少点名人数.
        /// </summary>
        public static string S_Shortcut_DecreaseRollCallCount {
            get {
                return ResourceManager.GetString("S_Shortcut_DecreaseRollCallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用快捷键.
        /// </summary>
        public static string S_Shortcut_Enable {
            get {
                return ResourceManager.GetString("S_Shortcut_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用全局快捷键响应。.
        /// </summary>
        public static string S_Shortcut_Enable_D {
            get {
                return ResourceManager.GetString("S_Shortcut_Enable_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加抽奖数量.
        /// </summary>
        public static string S_Shortcut_IncreaseLotteryCount {
            get {
                return ResourceManager.GetString("S_Shortcut_IncreaseLotteryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加点名人数.
        /// </summary>
        public static string S_Shortcut_IncreaseRollCallCount {
            get {
                return ResourceManager.GetString("S_Shortcut_IncreaseRollCallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开抽奖页.
        /// </summary>
        public static string S_Shortcut_OpenLotteryPage {
            get {
                return ResourceManager.GetString("S_Shortcut_OpenLotteryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置打开抽奖页的快捷键。.
        /// </summary>
        public static string S_Shortcut_OpenLotteryPage_D {
            get {
                return ResourceManager.GetString("S_Shortcut_OpenLotteryPage_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开点名页.
        /// </summary>
        public static string S_Shortcut_OpenRollCallPage {
            get {
                return ResourceManager.GetString("S_Shortcut_OpenRollCallPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置打开点名页的快捷键。.
        /// </summary>
        public static string S_Shortcut_OpenRollCallPage_D {
            get {
                return ResourceManager.GetString("S_Shortcut_OpenRollCallPage_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行闪抽.
        /// </summary>
        public static string S_Shortcut_QuickDraw {
            get {
                return ResourceManager.GetString("S_Shortcut_QuickDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置执行快速抽取的快捷键。.
        /// </summary>
        public static string S_Shortcut_QuickDraw_D {
            get {
                return ResourceManager.GetString("S_Shortcut_QuickDraw_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始或停止抽奖.
        /// </summary>
        public static string S_Shortcut_StartLottery {
            get {
                return ResourceManager.GetString("S_Shortcut_StartLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始或停止点名.
        /// </summary>
        public static string S_Shortcut_StartRollCall {
            get {
                return ResourceManager.GetString("S_Shortcut_StartRollCall", resourceCulture);
            }
        }
    }
}
