//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.More {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.More.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string C_ShortcutExampleLottery => ResourceManager.GetString("C_ShortcutExampleLottery", resourceCulture);
        public static string C_ShortcutExampleQuickDraw => ResourceManager.GetString("C_ShortcutExampleQuickDraw", resourceCulture);
        public static string C_ShortcutExampleRollCall => ResourceManager.GetString("C_ShortcutExampleRollCall", resourceCulture);
        public static string O_Left => ResourceManager.GetString("O_Left", resourceCulture);
        public static string O_Right => ResourceManager.GetString("O_Right", resourceCulture);
        public static string Page_Title => ResourceManager.GetString("Page_Title", resourceCulture);
        public static string S_Music => ResourceManager.GetString("S_Music", resourceCulture);
        public static string S_Music_BackgroundLoop => ResourceManager.GetString("S_Music_BackgroundLoop", resourceCulture);
        public static string S_Music_BackgroundLoop_D => ResourceManager.GetString("S_Music_BackgroundLoop_D", resourceCulture);
        public static string S_PageManagement => ResourceManager.GetString("S_PageManagement", resourceCulture);
        public static string S_RollCallControls => ResourceManager.GetString("S_RollCallControls", resourceCulture);
        public static string S_RollCallControls_D => ResourceManager.GetString("S_RollCallControls_D", resourceCulture);
        public static string S_RollCallGenderSelector => ResourceManager.GetString("S_RollCallGenderSelector", resourceCulture);
        public static string S_RollCallListSelector => ResourceManager.GetString("S_RollCallListSelector", resourceCulture);
        public static string S_RollCallPanelPosition => ResourceManager.GetString("S_RollCallPanelPosition", resourceCulture);
        public static string S_RollCallPanelPosition_D => ResourceManager.GetString("S_RollCallPanelPosition_D", resourceCulture);
        public static string S_RollCallQuantityControl => ResourceManager.GetString("S_RollCallQuantityControl", resourceCulture);
        public static string S_RollCallQuantityLabel => ResourceManager.GetString("S_RollCallQuantityLabel", resourceCulture);
        public static string S_RollCallRangeSelector => ResourceManager.GetString("S_RollCallRangeSelector", resourceCulture);
        public static string S_RollCallRemainingButton => ResourceManager.GetString("S_RollCallRemainingButton", resourceCulture);
        public static string S_RollCallResetButton => ResourceManager.GetString("S_RollCallResetButton", resourceCulture);
        public static string S_RollCallStartButton => ResourceManager.GetString("S_RollCallStartButton", resourceCulture);
        public static string S_Shortcut => ResourceManager.GetString("S_Shortcut", resourceCulture);
        public static string S_Shortcut_Enable => ResourceManager.GetString("S_Shortcut_Enable", resourceCulture);
        public static string S_Shortcut_Enable_D => ResourceManager.GetString("S_Shortcut_Enable_D", resourceCulture);
        public static string S_Shortcut_OpenLotteryPage => ResourceManager.GetString("S_Shortcut_OpenLotteryPage", resourceCulture);
        public static string S_Shortcut_OpenLotteryPage_D => ResourceManager.GetString("S_Shortcut_OpenLotteryPage_D", resourceCulture);
        public static string S_Shortcut_OpenRollCallPage => ResourceManager.GetString("S_Shortcut_OpenRollCallPage", resourceCulture);
        public static string S_Shortcut_OpenRollCallPage_D => ResourceManager.GetString("S_Shortcut_OpenRollCallPage_D", resourceCulture);
        public static string S_Shortcut_QuickDraw => ResourceManager.GetString("S_Shortcut_QuickDraw", resourceCulture);
        public static string S_Shortcut_QuickDraw_D => ResourceManager.GetString("S_Shortcut_QuickDraw_D", resourceCulture);
    }
}
