//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.ProfileSettings.Students {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Looks up a localized string similar to 添加学生.
        /// </summary>
        public static string Command_AddStudent {
            get {
                return ResourceManager.GetString("Command_AddStudent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除名单.
        /// </summary>
        public static string Command_DeleteList {
            get {
                return ResourceManager.GetString("Command_DeleteList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除学生.
        /// </summary>
        public static string Command_DeleteStudent {
            get {
                return ResourceManager.GetString("Command_DeleteStudent", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.ProfileSettings.Students.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string Command_CreateList {
            get {
                return ResourceManager.GetString("Command_CreateList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 新建一个名单。.
        /// </summary>
        public static string Command_CreateList_D {
            get {
                return ResourceManager.GetString("Command_CreateList_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Command_DuplicateList {
            get {
                return ResourceManager.GetString("Command_DuplicateList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 复制一个当前选中的名单的副本。.
        /// </summary>
        public static string Command_DuplicateList_D {
            get {
                return ResourceManager.GetString("Command_DuplicateList_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入学生.
        /// </summary>
        public static string Command_ImportStudents {
            get {
                return ResourceManager.GetString("Command_ImportStudents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Column_Gender {
            get {
                return ResourceManager.GetString("Column_Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 分组.
        /// </summary>
        public static string Column_Group {
            get {
                return ResourceManager.GetString("Column_Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 编号.
        /// </summary>
        public static string Column_Id {
            get {
                return ResourceManager.GetString("Column_Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string Column_Name {
            get {
                return ResourceManager.GetString("Column_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string Column_Exists {
            get {
                return ResourceManager.GetString("Column_Exists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 性别.
        /// </summary>
        public static string Field_Gender {
            get {
                return ResourceManager.GetString("Field_Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 分组.
        /// </summary>
        public static string Field_Group {
            get {
                return ResourceManager.GetString("Field_Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 编号.
        /// </summary>
        public static string Field_Id {
            get {
                return ResourceManager.GetString("Field_Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string Field_Exists {
            get {
                return ResourceManager.GetString("Field_Exists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 附加设置.
        /// </summary>
        public static string Section_AttachedSettings {
            get {
                return ResourceManager.GetString("Section_AttachedSettings", resourceCulture);
            }
        }
    }
}
