//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.General.Backup {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.General.Backup.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string C_Backups_DateTime {
            get {
                return ResourceManager.GetString("C_Backups_DateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 文件名.
        /// </summary>
        public static string C_Backups_FileName {
            get {
                return ResourceManager.GetString("C_Backups_FileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string C_Backups_Operations {
            get {
                return ResourceManager.GetString("C_Backups_Operations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string C_Backups_Operations_Delete {
            get {
                return ResourceManager.GetString("C_Backups_Operations_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复.
        /// </summary>
        public static string C_Backups_Operations_Restore {
            get {
                return ResourceManager.GetString("C_Backups_Operations_Restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 大小.
        /// </summary>
        public static string C_Backups_Size {
            get {
                return ResourceManager.GetString("C_Backups_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 刷新备份.
        /// </summary>
        public static string C_RefreshBackups {
            get {
                return ResourceManager.GetString("C_RefreshBackups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已创建备份：{0}.
        /// </summary>
        public static string M_BackupCreated {
            get {
                return ResourceManager.GetString("M_BackupCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份失败.
        /// </summary>
        public static string M_BackupFailed {
            get {
                return ResourceManager.GetString("M_BackupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份文件不存在，请刷新后重试.
        /// </summary>
        public static string M_BackupFileMissing {
            get {
                return ResourceManager.GetString("M_BackupFileMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 确定要删除备份“{0}”吗？此操作无法撤销。.
        /// </summary>
        public static string M_DeleteContent {
            get {
                return ResourceManager.GetString("M_DeleteContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除备份失败.
        /// </summary>
        public static string M_DeleteFailed {
            get {
                return ResourceManager.GetString("M_DeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string M_DeletePrimary {
            get {
                return ResourceManager.GetString("M_DeletePrimary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已删除备份.
        /// </summary>
        public static string M_DeleteSuccess {
            get {
                return ResourceManager.GetString("M_DeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除备份.
        /// </summary>
        public static string M_DeleteTitle {
            get {
                return ResourceManager.GetString("M_DeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份文件包含非法路径，已取消恢复.
        /// </summary>
        public static string M_InvalidBackupFile {
            get {
                return ResourceManager.GetString("M_InvalidBackupFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请至少选择一项备份内容.
        /// </summary>
        public static string M_NoBackupContentSelected {
            get {
                return ResourceManager.GetString("M_NoBackupContentSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复“{0}”会覆盖当前对应数据。恢复前会自动创建一份当前数据快照，恢复完成后需要重启应用。.
        /// </summary>
        public static string M_RestoreContent {
            get {
                return ResourceManager.GetString("M_RestoreContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复备份失败.
        /// </summary>
        public static string M_RestoreFailed {
            get {
                return ResourceManager.GetString("M_RestoreFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复.
        /// </summary>
        public static string M_RestorePrimary {
            get {
                return ResourceManager.GetString("M_RestorePrimary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份已恢复，请重启应用后生效.
        /// </summary>
        public static string M_RestoreSuccess {
            get {
                return ResourceManager.GetString("M_RestoreSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复备份.
        /// </summary>
        public static string M_RestoreTitle {
            get {
                return ResourceManager.GetString("M_RestoreTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份.
        /// </summary>
        public static string S_AutoBackup {
            get {
                return ResourceManager.GetString("S_AutoBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 是否启用自动备份.
        /// </summary>
        public static string S_AutoBackup_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份间隔.
        /// </summary>
        public static string S_AutoBackup_IntervalDays {
            get {
                return ResourceManager.GetString("S_AutoBackup_IntervalDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置自动备份间隔（天）.
        /// </summary>
        public static string S_AutoBackup_IntervalDays_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_IntervalDays_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即备份.
        /// </summary>
        public static string S_AutoBackup_ManualBackup {
            get {
                return ResourceManager.GetString("S_AutoBackup_ManualBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即创建一份全量备份.
        /// </summary>
        public static string S_AutoBackup_ManualBackup_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_ManualBackup_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份上限.
        /// </summary>
        public static string S_AutoBackup_MaxCount {
            get {
                return ResourceManager.GetString("S_AutoBackup_MaxCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置自动备份最多保留数量（个），0为不限制.
        /// </summary>
        public static string S_AutoBackup_MaxCount_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_MaxCount_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份占用大小.
        /// </summary>
        public static string S_AutoBackup_Usage {
            get {
                return ResourceManager.GetString("S_AutoBackup_Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份文件夹占用大小.
        /// </summary>
        public static string S_AutoBackup_Usage_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_Usage_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 占用大小.
        /// </summary>
        public static string S_AutoBackup_Usage_R {
            get {
                return ResourceManager.GetString("S_AutoBackup_Usage_R", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 查看备份文件.
        /// </summary>
        public static string S_AutoBackup_ViewFolder {
            get {
                return ResourceManager.GetString("S_AutoBackup_ViewFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开备份文件夹.
        /// </summary>
        public static string S_AutoBackup_ViewFolder_D {
            get {
                return ResourceManager.GetString("S_AutoBackup_ViewFolder_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份内容.
        /// </summary>
        public static string S_Includes {
            get {
                return ResourceManager.GetString("S_Includes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 音频资源.
        /// </summary>
        public static string S_Includes_Audio {
            get {
                return ResourceManager.GetString("S_Includes_Audio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 音频资源文件（audio）.
        /// </summary>
        public static string S_Includes_Audio_D {
            get {
                return ResourceManager.GetString("S_Includes_Audio_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 配置文件.
        /// </summary>
        public static string S_Includes_Config {
            get {
                return ResourceManager.GetString("S_Includes_Config", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 软件设置与配置文件（config）.
        /// </summary>
        public static string S_Includes_Config_D {
            get {
                return ResourceManager.GetString("S_Includes_Config_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CSES 联动.
        /// </summary>
        public static string S_Includes_Cses {
            get {
                return ResourceManager.GetString("S_Includes_Cses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CSES 相关联动数据（CSES）.
        /// </summary>
        public static string S_Includes_Cses_D {
            get {
                return ResourceManager.GetString("S_Includes_Cses_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择需要包含在备份文件中的数据.
        /// </summary>
        public static string S_Includes_D {
            get {
                return ResourceManager.GetString("S_Includes_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string S_Includes_History {
            get {
                return ResourceManager.GetString("S_Includes_History", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取历史记录数据（history）.
        /// </summary>
        public static string S_Includes_History_D {
            get {
                return ResourceManager.GetString("S_Includes_History_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取证明文件.
        /// </summary>
        public static string S_Includes_Proofs {
            get {
                return ResourceManager.GetString("S_Includes_Proofs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 可复现和核验抽取结果的证明文件（proofs）.
        /// </summary>
        public static string S_Includes_Proofs_D {
            get {
                return ResourceManager.GetString("S_Includes_Proofs_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 图片资源.
        /// </summary>
        public static string S_Includes_Images {
            get {
                return ResourceManager.GetString("S_Includes_Images", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 学生/奖品图片资源（images）.
        /// </summary>
        public static string S_Includes_Images_D {
            get {
                return ResourceManager.GetString("S_Includes_Images_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 名单数据.
        /// </summary>
        public static string S_Includes_List {
            get {
                return ResourceManager.GetString("S_Includes_List", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点名/抽奖名单等数据（list）.
        /// </summary>
        public static string S_Includes_List_D {
            get {
                return ResourceManager.GetString("S_Includes_List_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 运行日志.
        /// </summary>
        public static string S_Includes_Logs {
            get {
                return ResourceManager.GetString("S_Includes_Logs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 程序运行日志，可能包含敏感信息（logs）.
        /// </summary>
        public static string S_Includes_Logs_D {
            get {
                return ResourceManager.GetString("S_Includes_Logs_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复备份.
        /// </summary>
        public static string S_RestoreBackup {
            get {
                return ResourceManager.GetString("S_RestoreBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 不完整.
        /// </summary>
        public static string C_CloudBackup_Incomplete {
            get {
                return ResourceManager.GetString("C_CloudBackup_Incomplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 备份.
        /// </summary>
        public static string C_CloudBackup_Backups_FileName {
            get {
                return ResourceManager.GetString("C_CloudBackup_Backups_FileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 上传时间.
        /// </summary>
        public static string C_CloudBackup_Backups_DateTime {
            get {
                return ResourceManager.GetString("C_CloudBackup_Backups_DateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string C_CloudBackup_Backups_Operations {
            get {
                return ResourceManager.GetString("C_CloudBackup_Backups_Operations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 下载恢复.
        /// </summary>
        public static string C_CloudBackup_Backups_Restore {
            get {
                return ResourceManager.GetString("C_CloudBackup_Backups_Restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 大小.
        /// </summary>
        public static string C_CloudBackup_Backups_Size {
            get {
                return ResourceManager.GetString("C_CloudBackup_Backups_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 取消上传.
        /// </summary>
        public static string C_CloudBackup_Cancel {
            get {
                return ResourceManager.GetString("C_CloudBackup_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 清理不完整备份.
        /// </summary>
        public static string C_CloudBackup_Cleanup {
            get {
                return ResourceManager.GetString("C_CloudBackup_Cleanup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 未登录.
        /// </summary>
        public static string C_CloudBackup_NotSignedIn {
            get {
                return ResourceManager.GetString("C_CloudBackup_NotSignedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}（本应用 {2}）.
        /// </summary>
        public static string C_CloudBackup_QuotaUsage {
            get {
                return ResourceManager.GetString("C_CloudBackup_QuotaUsage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 刷新云端空间用量.
        /// </summary>
        public static string C_CloudBackup_QuotaRefresh {
            get {
                return ResourceManager.GetString("C_CloudBackup_QuotaRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 刷新云端备份.
        /// </summary>
        public static string C_CloudBackup_Refresh {
            get {
                return ResourceManager.GetString("C_CloudBackup_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 登录账号.
        /// </summary>
        public static string C_CloudBackup_SignIn {
            get {
                return ResourceManager.GetString("C_CloudBackup_SignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string C_CloudBackup_SignedInAs {
            get {
                return ResourceManager.GetString("C_CloudBackup_SignedInAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 开始上传.
        /// </summary>
        public static string C_CloudBackup_Upload {
            get {
                return ResourceManager.GetString("C_CloudBackup_Upload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份.
        /// </summary>
        public static string C_Tab_CloudBackup {
            get {
                return ResourceManager.GetString("C_Tab_CloudBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 本地备份.
        /// </summary>
        public static string C_Tab_LocalBackup {
            get {
                return ResourceManager.GetString("C_Tab_LocalBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 清理不完整备份失败.
        /// </summary>
        public static string M_CloudCleanupFailed {
            get {
                return ResourceManager.GetString("M_CloudCleanupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已清理 {0} 份不完整备份.
        /// </summary>
        public static string M_CloudCleanupSuccess {
            get {
                return ResourceManager.GetString("M_CloudCleanupSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 确定要删除云端备份“{0}”吗？此操作无法撤销.
        /// </summary>
        public static string M_CloudDeleteContent {
            get {
                return ResourceManager.GetString("M_CloudDeleteContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除云端备份失败.
        /// </summary>
        public static string M_CloudDeleteFailed {
            get {
                return ResourceManager.GetString("M_CloudDeleteFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已删除云端备份.
        /// </summary>
        public static string M_CloudDeleteSuccess {
            get {
                return ResourceManager.GetString("M_CloudDeleteSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 删除云端备份.
        /// </summary>
        public static string M_CloudDeleteTitle {
            get {
                return ResourceManager.GetString("M_CloudDeleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份下载失败.
        /// </summary>
        public static string M_CloudDownloadFailed {
            get {
                return ResourceManager.GetString("M_CloudDownloadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该云端备份不完整，无法恢复.
        /// </summary>
        public static string M_CloudIncomplete {
            get {
                return ResourceManager.GetString("M_CloudIncomplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 清理中ing~.
        /// </summary>
        public static string M_CloudCleaning {
            get {
                return ResourceManager.GetString("M_CloudCleaning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云空间不足，请清理云端备份后重试.
        /// </summary>
        public static string M_CloudQuotaExceeded {
            get {
                return ResourceManager.GetString("M_CloudQuotaExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 正在获取.
        /// </summary>
        public static string M_CloudQuotaLoading {
            get {
                return ResourceManager.GetString("M_CloudQuotaLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法获取云端空间用量.
        /// </summary>
        public static string M_CloudQuotaUnknown {
            get {
                return ResourceManager.GetString("M_CloudQuotaUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法打开云储存页面.
        /// </summary>
        public static string M_CloudStoragePageFailed {
            get {
                return ResourceManager.GetString("M_CloudStoragePageFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 刷新中ing~.
        /// </summary>
        public static string M_CloudRefreshing {
            get {
                return ResourceManager.GetString("M_CloudRefreshing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 获取云端备份列表失败.
        /// </summary>
        public static string M_CloudRefreshFailed {
            get {
                return ResourceManager.GetString("M_CloudRefreshFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复云端备份“{0}”会覆盖当前对应数据；恢复前会自动创建一份当前数据快照，恢复完成后需要重启应用.
        /// </summary>
        public static string M_CloudRestoreContent {
            get {
                return ResourceManager.GetString("M_CloudRestoreContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 恢复云端备份失败.
        /// </summary>
        public static string M_CloudRestoreFailed {
            get {
                return ResourceManager.GetString("M_CloudRestoreFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份已恢复，请重启应用后生效.
        /// </summary>
        public static string M_CloudRestoreSuccess {
            get {
                return ResourceManager.GetString("M_CloudRestoreSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 从云端恢复.
        /// </summary>
        public static string M_CloudRestoreTitle {
            get {
                return ResourceManager.GetString("M_CloudRestoreTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SECTL 尚未为该应用启用云服务.
        /// </summary>
        public static string M_CloudServiceDisabled {
            get {
                return ResourceManager.GetString("M_CloudServiceDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 请先登录 SECTL 账号.
        /// </summary>
        public static string M_CloudSignInRequired {
            get {
                return ResourceManager.GetString("M_CloudSignInRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SECTL 登录状态已失效，请重新登录.
        /// </summary>
        public static string M_CloudSignedOut {
            get {
                return ResourceManager.GetString("M_CloudSignedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份上传已取消.
        /// </summary>
        public static string M_CloudUploadCancelled {
            get {
                return ResourceManager.GetString("M_CloudUploadCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 上传中ing~.
        /// </summary>
        public static string M_CloudUploading {
            get {
                return ResourceManager.GetString("M_CloudUploading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份上传失败.
        /// </summary>
        public static string M_CloudUploadFailed {
            get {
                return ResourceManager.GetString("M_CloudUploadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份上传完成.
        /// </summary>
        public static string M_CloudUploadSuccess {
            get {
                return ResourceManager.GetString("M_CloudUploadSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端服务响应超时，可能是服务端负载过高，请稍后重试.
        /// </summary>
        public static string M_CloudServerTimeout {
            get {
                return ResourceManager.GetString("M_CloudServerTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端服务暂时不可用，请稍后重试.
        /// </summary>
        public static string M_CloudServerError {
            get {
                return ResourceManager.GetString("M_CloudServerError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 若云端残留未完成的分片，可使用“清理不完整备份”移除.
        /// </summary>
        public static string M_CloudUploadCleanupHint {
            get {
                return ResourceManager.GetString("M_CloudUploadCleanupHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份.
        /// </summary>
        public static string S_CloudBackup {
            get {
                return ResourceManager.GetString("S_CloudBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 账号状态.
        /// </summary>
        public static string S_CloudBackup_Account {
            get {
                return ResourceManager.GetString("S_CloudBackup_Account", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 当前用于云同步的 SECTL 账号.
        /// </summary>
        public static string S_CloudBackup_Account_D {
            get {
                return ResourceManager.GetString("S_CloudBackup_Account_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 登录 SECTL 账号后可将数据备份上传到云端并随时恢复.
        /// </summary>
        public static string S_CloudBackup_D {
            get {
                return ResourceManager.GetString("S_CloudBackup_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份管理.
        /// </summary>
        public static string S_CloudBackup_List {
            get {
                return ResourceManager.GetString("S_CloudBackup_List", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已上传的云端备份，可下载恢复或删除.
        /// </summary>
        public static string S_CloudBackup_List_D {
            get {
                return ResourceManager.GetString("S_CloudBackup_List_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择需要包含在备份文件中的数据.
        /// </summary>
        public static string S_CloudIncludes_D {
            get {
                return ResourceManager.GetString("S_CloudIncludes_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设备别名.
        /// </summary>
        public static string S_CloudDeviceAlias {
            get {
                return ResourceManager.GetString("S_CloudDeviceAlias", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用于区分不同设备的云端备份，会显示在云端文件名中；留空则使用本机名称.
        /// </summary>
        public static string S_CloudDeviceAlias_D {
            get {
                return ResourceManager.GetString("S_CloudDeviceAlias_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端备份内容.
        /// </summary>
        public static string S_CloudIncludes {
            get {
                return ResourceManager.GetString("S_CloudIncludes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端自动备份.
        /// </summary>
        public static string S_CloudAutoBackup {
            get {
                return ResourceManager.GetString("S_CloudAutoBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 按设定的间隔自动备份到云端，云空间不足时会删除整个账号最早的云端备份.
        /// </summary>
        public static string S_CloudAutoBackup_D {
            get {
                return ResourceManager.GetString("S_CloudAutoBackup_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份间隔.
        /// </summary>
        public static string S_CloudAutoBackup_IntervalDays {
            get {
                return ResourceManager.GetString("S_CloudAutoBackup_IntervalDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置云端自动备份间隔（天）.
        /// </summary>
        public static string S_CloudAutoBackup_IntervalDays_D {
            get {
                return ResourceManager.GetString("S_CloudAutoBackup_IntervalDays_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自动备份上限.
        /// </summary>
        public static string S_CloudAutoBackup_MaxCount {
            get {
                return ResourceManager.GetString("S_CloudAutoBackup_MaxCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置本设备在云端最多保留的备份数量（个），0为不限制，超出后自动删除本设备最早的备份.
        /// </summary>
        public static string S_CloudAutoBackup_MaxCount_D {
            get {
                return ResourceManager.GetString("S_CloudAutoBackup_MaxCount_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 云端空间.
        /// </summary>
        public static string S_CloudBackup_Quota {
            get {
                return ResourceManager.GetString("S_CloudBackup_Quota", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 当前账号的云空间用量与本应用占用.
        /// </summary>
        public static string S_CloudBackup_Quota_D {
            get {
                return ResourceManager.GetString("S_CloudBackup_Quota_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用量.
        /// </summary>
        public static string S_CloudBackup_Quota_R {
            get {
                return ResourceManager.GetString("S_CloudBackup_Quota_R", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开 思拓创联 云储存页面.
        /// </summary>
        public static string S_CloudBackup_OpenStoragePage {
            get {
                return ResourceManager.GetString("S_CloudBackup_OpenStoragePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 在浏览器中打开 SECTL 云储存网页，查看与管理云端文件.
        /// </summary>
        public static string S_CloudBackup_OpenStoragePage_D {
            get {
                return ResourceManager.GetString("S_CloudBackup_OpenStoragePage_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即备份到云端.
        /// </summary>
        public static string S_CloudBackup_Upload {
            get {
                return ResourceManager.GetString("S_CloudBackup_Upload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 将所选数据打包上传到云端.
        /// </summary>
        public static string S_CloudBackup_Upload_D {
            get {
                return ResourceManager.GetString("S_CloudBackup_Upload_D", resourceCulture);
            }
        }
    }
}
