<Project>

    <PropertyGroup>
        <FluentIconMappingNamespace>SecRandom.Core.FluentIcons</FluentIconMappingNamespace>
        <FluentIconMappingClassName>FI</FluentIconMappingClassName>
        <FluentIconMappingFile>Assets/FluentSystemIcons-Resizable.json</FluentIconMappingFile>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="FluentIconMappingNamespace" />
        <CompilerVisibleProperty Include="FluentIconMappingClassName" />
        <CompilerVisibleProperty Include="FluentIconMappingFile" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\vendors\SecRandom.FluentIconMappingGenerator\SecRandom.FluentIconMappingGenerator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />

        <AdditionalFiles Include="$(MSBuildProjectDirectory)\$(FluentIconMappingFile)" />
    </ItemGroup>
</Project>