// <auto-generated />
#nullable enable
namespace SecRandom.Langs.SettingsPages.Announcements;

using System.Globalization;
using System.Resources;

public static class Resources
{
    private static readonly ResourceManager Manager = new("SecRandom.Langs.SettingsPages.Announcements.Resources", typeof(Resources).Assembly);
    public static CultureInfo? Culture { get; set; }
    public static string Page_Title => Manager.GetString("Page_Title", Culture) ?? "Announcements";
    public static string C_Refresh => Manager.GetString("C_Refresh", Culture) ?? "Refresh announcements";
    public static string C_Pinned => Manager.GetString("C_Pinned", Culture) ?? "Pinned";
    public static string M_LoadError => Manager.GetString("M_LoadError", Culture) ?? "Announcements could not be loaded. Try again later.";
    public static string M_NetworkError => Manager.GetString("M_NetworkError", Culture) ?? "Unable to connect to the announcement service. Check your network and try again.";
    public static string M_Empty => Manager.GetString("M_Empty", Culture) ?? "No announcements";
}
