//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Personalized.Timer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Personalized.Timer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 秒.
        /// </summary>
        public static string C_Preset30s {
            get {
                return ResourceManager.GetString("C_Preset30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 分钟.
        /// </summary>
        public static string C_Preset1m {
            get {
                return ResourceManager.GetString("C_Preset1m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 分钟.
        /// </summary>
        public static string C_Preset5m {
            get {
                return ResourceManager.GetString("C_Preset5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计时器.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动缩小为小窗.
        /// </summary>
        public static string S_AutoMiniWindow {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停留在计时器页面且一段时间没有任何操作后自动关闭大窗并打开置顶小窗.
        /// </summary>
        public static string S_AutoMiniWindow_D {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时钟.
        /// </summary>
        public static string S_AutoMiniWindow_Clock {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时钟页面无操作到设定时长后自动缩成小窗.
        /// </summary>
        public static string S_AutoMiniWindow_Clock_D {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Clock_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 倒计时.
        /// </summary>
        public static string S_AutoMiniWindow_Countdown {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 倒计时页面无操作到设定时长后自动缩成小窗.
        /// </summary>
        public static string S_AutoMiniWindow_Countdown_D {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Countdown_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动缩小时间.
        /// </summary>
        public static string S_AutoMiniWindow_Seconds {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面多久没有任何操作之后自动缩成小窗（打开页面本身算一次操作）.
        /// </summary>
        public static string S_AutoMiniWindow_Seconds_D {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Seconds_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒表.
        /// </summary>
        public static string S_AutoMiniWindow_Stopwatch {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Stopwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒表页面无操作到设定时长后自动缩成小窗.
        /// </summary>
        public static string S_AutoMiniWindow_Stopwatch_D {
            get {
                return ResourceManager.GetString("S_AutoMiniWindow_Stopwatch_D", resourceCulture);
            }
        }
    }
}
