<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <!--If you are willing to use platform-specific APIs, use conditional compilation.
        See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <EnableGitInfoGenerator>true</EnableGitInfoGenerator>
        <ApplicationIcon>..\SecRandom\Assets\AppLogo.ico</ApplicationIcon>
        <!-- Arch Linux reports an unsupported arch-x64 RID when no RID is specified. -->
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and $([System.OperatingSystem]::IsLinux()) and $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'X64'">linux-x64</RuntimeIdentifier>
        <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and $([System.OperatingSystem]::IsLinux()) and $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'Arm64'">linux-arm64</RuntimeIdentifier>
    </PropertyGroup>

    <Import Project="..\Platforms.props" />

    <PropertyGroup>
        <EnableUiAccess Condition="'$(EnableUiAccess)' == ''">false</EnableUiAccess>
        <ApplicationManifest Condition="'$(EnableUiAccess)' != 'true'">app.manifest</ApplicationManifest>
        <ApplicationManifest Condition="'$(EnableUiAccess)' == 'true'">app.uiaccess.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Sentry.Extensions.Logging" Version="6.7.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SecRandom\SecRandom.csproj"/>
        <ProjectReference Include="..\SecRandom.Platforms\SecRandom.Platforms.csproj" />
        <ProjectReference Include="..\SecRandom.Platforms.Abstractions\SecRandom.Platforms.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(SecRandomPlatform)' == 'Windows'">
        <ProjectReference Include="..\SecRandom.Platforms.Windows\SecRandom.Platforms.Windows.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(SecRandomPlatform)' == 'Linux'">
        <ProjectReference Include="..\SecRandom.Platforms.Linux\SecRandom.Platforms.Linux.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(SecRandomPlatform)' == 'MacOs'">
        <ProjectReference Include="..\SecRandom.Platforms.MacOs\SecRandom.Platforms.MacOs.csproj" />
    </ItemGroup>

    <Import Project="..\Global.props"/>
</Project>
