//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.CrashRecovery {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.CrashRecovery.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string C_Close => ResourceManager.GetString("C_Close", resourceCulture);
        public static string C_CopyDone => ResourceManager.GetString("C_CopyDone", resourceCulture);
        public static string C_CopyFailed => ResourceManager.GetString("C_CopyFailed", resourceCulture);
        public static string C_CopyReport => ResourceManager.GetString("C_CopyReport", resourceCulture);
        public static string C_ReportFailed => ResourceManager.GetString("C_ReportFailed", resourceCulture);
        public static string C_ReportIssue => ResourceManager.GetString("C_ReportIssue", resourceCulture);
        public static string C_Ignore => ResourceManager.GetString("C_Ignore", resourceCulture);
        public static string C_Restart => ResourceManager.GetString("C_Restart", resourceCulture);
        public static string C_RestartCountdown => ResourceManager.GetString("C_RestartCountdown", resourceCulture);
        public static string Description => ResourceManager.GetString("Description", resourceCulture);
        public static string FeedbackBody => ResourceManager.GetString("FeedbackBody", resourceCulture);
        public static string FeedbackTitle => ResourceManager.GetString("FeedbackTitle", resourceCulture);
        public static string NoStackTrace => ResourceManager.GetString("NoStackTrace", resourceCulture);
        public static string ReportUnavailable => ResourceManager.GetString("ReportUnavailable", resourceCulture);
        public static string Title => ResourceManager.GetString("Title", resourceCulture);
    }
}
