//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ThemeManagement {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ThemeManagement.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 默认主题.
        /// </summary>
        public static string C_DefaultThemePlaceholder {
            get {
                return ResourceManager.GetString("C_DefaultThemePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 渐变.
        /// </summary>
        /// <summary>
        ///   Looks up a localized string similar to 图片文件.
        /// </summary>
        public static string C_ImageFileType {
            get {
                return ResourceManager.GetString("C_ImageFileType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择图片.
        /// </summary>
        public static string C_SelectImage {
            get {
                return ResourceManager.GetString("C_SelectImage", resourceCulture);
            }
        }

        public static string O_BackgroundMode_Gradient {
            get {
                return ResourceManager.GetString("O_BackgroundMode_Gradient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string O_BackgroundMode_Image {
            get {
                return ResourceManager.GetString("O_BackgroundMode_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 纯色.
        /// </summary>
        public static string O_BackgroundMode_Solid {
            get {
                return ResourceManager.GetString("O_BackgroundMode_Solid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string O_BackgroundMode_System {
            get {
                return ResourceManager.GetString("O_BackgroundMode_System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主题管理.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主窗口背景.
        /// </summary>
        public static string S_MainWindowBackground {
            get {
                return ResourceManager.GetString("S_MainWindowBackground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用背景模糊.
        /// </summary>
        public static string S_MainWindowBackground_Blur {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Blur", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 为背景图片启用模糊处理。.
        /// </summary>
        public static string S_MainWindowBackground_Blur_D {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Blur_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景模糊半径.
        /// </summary>
        public static string S_MainWindowBackground_BlurRadius {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_BlurRadius", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置主窗口背景模糊处理的半径。.
        /// </summary>
        public static string S_MainWindowBackground_BlurRadius_D {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_BlurRadius_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景亮度.
        /// </summary>
        public static string S_MainWindowBackground_Brightness {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Brightness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 调整主窗口背景图片或颜色的亮度。.
        /// </summary>
        public static string S_MainWindowBackground_Brightness_D {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Brightness_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景颜色.
        /// </summary>
        public static string S_MainWindowBackground_Color {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主窗口纯色背景颜色。.
        /// </summary>
        public static string S_MainWindowBackground_Color_D {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Color_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 渐变起止颜色.
        /// </summary>
        public static string S_MainWindowBackground_Gradient {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Gradient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置主窗口渐变背景的起点和终点颜色。.
        /// </summary>
        public static string S_MainWindowBackground_Gradient_D {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Gradient_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景图片.
        /// </summary>
        public static string S_MainWindowBackground_Image {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 主窗口背景图片路径。.
        /// </summary>
        public static string S_MainWindowBackground_Image_D {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Image_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景模式.
        /// </summary>
        public static string S_MainWindowBackground_Mode {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择主窗口背景的呈现方式。.
        /// </summary>
        public static string S_MainWindowBackground_Mode_D {
            get {
                return ResourceManager.GetString("S_MainWindowBackground_Mode_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 页面主题.
        /// </summary>
        public static string S_PageTheme {
            get {
                return ResourceManager.GetString("S_PageTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽奖主题 ID.
        /// </summary>
        public static string S_PageTheme_LotteryThemeId {
            get {
                return ResourceManager.GetString("S_PageTheme_LotteryThemeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 为抽奖页面指定主题配置标识。.
        /// </summary>
        public static string S_PageTheme_LotteryThemeId_D {
            get {
                return ResourceManager.GetString("S_PageTheme_LotteryThemeId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 点名主题 ID.
        /// </summary>
        public static string S_PageTheme_RollCallThemeId {
            get {
                return ResourceManager.GetString("S_PageTheme_RollCallThemeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 为点名页面指定主题配置标识。.
        /// </summary>
        public static string S_PageTheme_RollCallThemeId_D {
            get {
                return ResourceManager.GetString("S_PageTheme_RollCallThemeId_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置窗口背景.
        /// </summary>
        public static string S_SettingsWindowBackground {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景颜色.
        /// </summary>
        public static string S_SettingsWindowBackground_Color {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置设置窗口的纯色背景颜色。.
        /// </summary>
        public static string S_SettingsWindowBackground_Color_D {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Color_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景模式.
        /// </summary>
        public static string S_SettingsWindowBackground_Mode {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择设置窗口背景的呈现方式。.
        /// </summary>
        public static string S_SettingsWindowBackground_Mode_D {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Mode_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 渐变方向.
        /// </summary>
        public static string S_Background_GradientDirection {
            get {
                return ResourceManager.GetString("S_Background_GradientDirection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择背景渐变的方向。.
        /// </summary>
        public static string S_Background_GradientDirection_D {
            get {
                return ResourceManager.GetString("S_Background_GradientDirection_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 从上到下.
        /// </summary>
        public static string O_GradientDirection_TopToBottom {
            get {
                return ResourceManager.GetString("O_GradientDirection_TopToBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 从下到上.
        /// </summary>
        public static string O_GradientDirection_BottomToTop {
            get {
                return ResourceManager.GetString("O_GradientDirection_BottomToTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 从左到右.
        /// </summary>
        public static string O_GradientDirection_LeftToRight {
            get {
                return ResourceManager.GetString("O_GradientDirection_LeftToRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 从右到左.
        /// </summary>
        public static string O_GradientDirection_RightToLeft {
            get {
                return ResourceManager.GetString("O_GradientDirection_RightToLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 左上到右下.
        /// </summary>
        public static string O_GradientDirection_TopLeftToBottomRight {
            get {
                return ResourceManager.GetString("O_GradientDirection_TopLeftToBottomRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 右下到左上.
        /// </summary>
        public static string O_GradientDirection_BottomRightToTopLeft {
            get {
                return ResourceManager.GetString("O_GradientDirection_BottomRightToTopLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 右上到左下.
        /// </summary>
        public static string O_GradientDirection_TopRightToBottomLeft {
            get {
                return ResourceManager.GetString("O_GradientDirection_TopRightToBottomLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 左下到右上.
        /// </summary>
        public static string O_GradientDirection_BottomLeftToTopRight {
            get {
                return ResourceManager.GetString("O_GradientDirection_BottomLeftToTopRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 渐变起止颜色.
        /// </summary>
        public static string S_SettingsWindowBackground_Gradient {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Gradient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置设置窗口渐变背景的起点和终点颜色。.
        /// </summary>
        public static string S_SettingsWindowBackground_Gradient_D {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Gradient_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景图片.
        /// </summary>
        public static string S_SettingsWindowBackground_Image {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置窗口背景图片路径。.
        /// </summary>
        public static string S_SettingsWindowBackground_Image_D {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Image_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景亮度.
        /// </summary>
        public static string S_SettingsWindowBackground_Brightness {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Brightness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 调整设置窗口背景图片或颜色的亮度。.
        /// </summary>
        public static string S_SettingsWindowBackground_Brightness_D {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Brightness_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用背景模糊.
        /// </summary>
        public static string S_SettingsWindowBackground_Blur {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Blur", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 为设置窗口背景图片启用模糊处理。.
        /// </summary>
        public static string S_SettingsWindowBackground_Blur_D {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_Blur_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景模糊半径.
        /// </summary>
        public static string S_SettingsWindowBackground_BlurRadius {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_BlurRadius", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置设置窗口背景模糊处理的半径。.
        /// </summary>
        public static string S_SettingsWindowBackground_BlurRadius_D {
            get {
                return ResourceManager.GetString("S_SettingsWindowBackground_BlurRadius_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 内置通知浮窗背景.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景模式.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Mode {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Mode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 选择内置通知浮窗背景的呈现方式。.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Mode_D {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Mode_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景颜色.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Color {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置内置通知浮窗的纯色背景颜色。.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Color_D {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Color_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 渐变起止颜色.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Gradient {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Gradient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置内置通知浮窗渐变背景的起点和终点颜色。.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Gradient_D {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Gradient_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景图片.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Image {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 内置通知浮窗背景图片路径。.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Image_D {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Image_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景亮度.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Brightness {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Brightness", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 调整内置通知浮窗背景图片或颜色的亮度。.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Brightness_D {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Brightness_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用背景模糊.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Blur {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Blur", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 为内置通知浮窗背景图片启用模糊处理。.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_Blur_D {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_Blur_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 背景模糊半径.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_BlurRadius {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_BlurRadius", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置内置通知浮窗背景模糊处理的半径。.
        /// </summary>
        public static string S_NotificationFloatingWindowBackground_BlurRadius_D {
            get {
                return ResourceManager.GetString("S_NotificationFloatingWindowBackground_BlurRadius_D", resourceCulture);
            }
        }
    }
}
