//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SecRandom.Mobile.Langs.Mobile;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(
    "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager =>
        resourceMan ??= new global::System.Resources.ResourceManager(
            "SecRandom.Mobile.Langs.Mobile.Resources", typeof(Resources).Assembly);

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string M_AndroidContextUnavailable => ResourceManager.GetString("M_AndroidContextUnavailable", resourceCulture)!;

    public static string M_AndroidOnlyInstaller => ResourceManager.GetString("M_AndroidOnlyInstaller", resourceCulture)!;

    public static string C_AddPrize => ResourceManager.GetString("C_AddPrize", resourceCulture)!;

    public static string C_Back => ResourceManager.GetString("C_Back", resourceCulture)!;

    public static string C_AddStudent => ResourceManager.GetString("C_AddStudent", resourceCulture)!;

    public static string C_CheckUpdates => ResourceManager.GetString("C_CheckUpdates", resourceCulture)!;

    public static string C_ClearTemporaryRecords => ResourceManager.GetString("C_ClearTemporaryRecords", resourceCulture)!;

    public static string C_DrawOne => ResourceManager.GetString("C_DrawOne", resourceCulture)!;

    public static string C_DrawPrize => ResourceManager.GetString("C_DrawPrize", resourceCulture)!;

    public static string C_InstallUpdate => ResourceManager.GetString("C_InstallUpdate", resourceCulture)!;

    public static string C_Lottery => ResourceManager.GetString("C_Lottery", resourceCulture)!;

    public static string C_ManagePrizePool => ResourceManager.GetString("C_ManagePrizePool", resourceCulture)!;

    public static string C_ManageStudentList => ResourceManager.GetString("C_ManageStudentList", resourceCulture)!;

    public static string C_Remove => ResourceManager.GetString("C_Remove", resourceCulture)!;

    public static string C_RollCall => ResourceManager.GetString("C_RollCall", resourceCulture)!;

    public static string M_CheckingUpdates => ResourceManager.GetString("M_CheckingUpdates", resourceCulture)!;

    public static string M_AboutLicense => ResourceManager.GetString("M_AboutLicense", resourceCulture)!;

    public static string M_CheckUpdatesFailed => ResourceManager.GetString("M_CheckUpdatesFailed", resourceCulture)!;

    public static string M_AddPrizesPrompt => ResourceManager.GetString("M_AddPrizesPrompt", resourceCulture)!;

    public static string M_AddStudentsPrompt => ResourceManager.GetString("M_AddStudentsPrompt", resourceCulture)!;

    public static string M_CandidatePrizes => ResourceManager.GetString("M_CandidatePrizes", resourceCulture)!;

    public static string M_CandidateStudents => ResourceManager.GetString("M_CandidateStudents", resourceCulture)!;

    public static string M_DownloadingUpdate => ResourceManager.GetString("M_DownloadingUpdate", resourceCulture)!;

    public static string M_EmptyMetadata => ResourceManager.GetString("M_EmptyMetadata", resourceCulture)!;

    public static string M_InstallUpdateFailed => ResourceManager.GetString("M_InstallUpdateFailed", resourceCulture)!;

    public static string M_DefaultList => ResourceManager.GetString("M_DefaultList", resourceCulture)!;

    public static string M_DefaultPool => ResourceManager.GetString("M_DefaultPool", resourceCulture)!;

    public static string M_Disabled => ResourceManager.GetString("M_Disabled", resourceCulture)!;

    public static string M_DrawCompleted => ResourceManager.GetString("M_DrawCompleted", resourceCulture)!;

    public static string M_DrawFailed => ResourceManager.GetString("M_DrawFailed", resourceCulture)!;

    public static string M_InstallerOpened => ResourceManager.GetString("M_InstallerOpened", resourceCulture)!;

    public static string M_ManifestInvalid => ResourceManager.GetString("M_ManifestInvalid", resourceCulture)!;

    public static string M_ManifestSignatureInvalid => ResourceManager.GetString("M_ManifestSignatureInvalid", resourceCulture)!;

    public static string M_ManifestTagMismatch => ResourceManager.GetString("M_ManifestTagMismatch", resourceCulture)!;

    public static string M_ManifestUnavailable => ResourceManager.GetString("M_ManifestUnavailable", resourceCulture)!;

    public static string M_MissingReleaseChannel => ResourceManager.GetString("M_MissingReleaseChannel", resourceCulture)!;

    public static string M_NoCandidates => ResourceManager.GetString("M_NoCandidates", resourceCulture)!;

    public static string M_NoEligibleCandidates => ResourceManager.GetString("M_NoEligibleCandidates", resourceCulture)!;

    public static string M_NoHistory => ResourceManager.GetString("M_NoHistory", resourceCulture)!;

    public static string M_NoPrizes => ResourceManager.GetString("M_NoPrizes", resourceCulture)!;

    public static string M_NoStudents => ResourceManager.GetString("M_NoStudents", resourceCulture)!;

    public static string M_PrizeId => ResourceManager.GetString("M_PrizeId", resourceCulture)!;

    public static string M_Ready => ResourceManager.GetString("M_Ready", resourceCulture)!;

    public static string M_RepeatLimitExhausted => ResourceManager.GetString("M_RepeatLimitExhausted", resourceCulture)!;

    public static string M_StudentId => ResourceManager.GetString("M_StudentId", resourceCulture)!;

    public static string M_Enabled => ResourceManager.GetString("M_Enabled", resourceCulture)!;

    public static string M_InvalidWeight => ResourceManager.GetString("M_InvalidWeight", resourceCulture)!;

    public static string M_LotteryRounds => ResourceManager.GetString("M_LotteryRounds", resourceCulture)!;

    public static string M_Prizes => ResourceManager.GetString("M_Prizes", resourceCulture)!;

    public static string M_RollCallRounds => ResourceManager.GetString("M_RollCallRounds", resourceCulture)!;

    public static string M_Students => ResourceManager.GetString("M_Students", resourceCulture)!;

    public static string M_OpeningInstaller => ResourceManager.GetString("M_OpeningInstaller", resourceCulture)!;

    public static string M_PackageHashInvalid => ResourceManager.GetString("M_PackageHashInvalid", resourceCulture)!;

    public static string M_PackageLengthInvalid => ResourceManager.GetString("M_PackageLengthInvalid", resourceCulture)!;

    public static string M_PackageUnavailable => ResourceManager.GetString("M_PackageUnavailable", resourceCulture)!;

    public static string M_StartupFailed => ResourceManager.GetString("M_StartupFailed", resourceCulture)!;

    public static string M_UpdateAvailable => ResourceManager.GetString("M_UpdateAvailable", resourceCulture)!;

    public static string M_UpToDate => ResourceManager.GetString("M_UpToDate", resourceCulture)!;

    public static string M_BackupMobileUnavailable => ResourceManager.GetString("M_BackupMobileUnavailable", resourceCulture)!;

    public static string M_GeneralMobileOnly => ResourceManager.GetString("M_GeneralMobileOnly", resourceCulture)!;

    public static string N_Draw => ResourceManager.GetString("N_Draw", resourceCulture)!;

    public static string N_History => ResourceManager.GetString("N_History", resourceCulture)!;

    public static string N_Overview => ResourceManager.GetString("N_Overview", resourceCulture)!;

    public static string N_Settings => ResourceManager.GetString("N_Settings", resourceCulture)!;

    public static string P_Draw => ResourceManager.GetString("P_Draw", resourceCulture)!;

    public static string P_History => ResourceManager.GetString("P_History", resourceCulture)!;

    public static string P_Overview => ResourceManager.GetString("P_Overview", resourceCulture)!;

    public static string P_Settings => ResourceManager.GetString("P_Settings", resourceCulture)!;

    public static string S_AppUpdates => ResourceManager.GetString("S_AppUpdates", resourceCulture)!;

    public static string S_AppUpdates_D => ResourceManager.GetString("S_AppUpdates_D", resourceCulture)!;

    public static string S_About => ResourceManager.GetString("S_About", resourceCulture)!;

    public static string S_About_D => ResourceManager.GetString("S_About_D", resourceCulture)!;

    public static string S_Backup => ResourceManager.GetString("S_Backup", resourceCulture)!;

    public static string S_Backup_D => ResourceManager.GetString("S_Backup_D", resourceCulture)!;

    public static string S_CurrentList => ResourceManager.GetString("S_CurrentList", resourceCulture)!;

    public static string S_CurrentPool => ResourceManager.GetString("S_CurrentPool", resourceCulture)!;

    public static string S_DataOverview => ResourceManager.GetString("S_DataOverview", resourceCulture)!;

    public static string S_DrawSettings => ResourceManager.GetString("S_DrawSettings", resourceCulture)!;

    public static string S_DrawSettings_D => ResourceManager.GetString("S_DrawSettings_D", resourceCulture)!;

    public static string S_General => ResourceManager.GetString("S_General", resourceCulture)!;

    public static string S_General_D => ResourceManager.GetString("S_General_D", resourceCulture)!;

    public static string S_ListManagement => ResourceManager.GetString("S_ListManagement", resourceCulture)!;

    public static string S_ListManagement_D => ResourceManager.GetString("S_ListManagement_D", resourceCulture)!;

    public static string S_Lottery => ResourceManager.GetString("S_Lottery", resourceCulture)!;

    public static string S_Personalization => ResourceManager.GetString("S_Personalization", resourceCulture)!;

    public static string S_Personalization_D => ResourceManager.GetString("S_Personalization_D", resourceCulture)!;

    public static string S_PrizePool => ResourceManager.GetString("S_PrizePool", resourceCulture)!;

    public static string S_RecentDraws => ResourceManager.GetString("S_RecentDraws", resourceCulture)!;

    public static string S_StudentList => ResourceManager.GetString("S_StudentList", resourceCulture)!;

    public static string S_RollCall => ResourceManager.GetString("S_RollCall", resourceCulture)!;

    public static string S_RepeatMode => ResourceManager.GetString("S_RepeatMode", resourceCulture)!;

    public static string S_HalfRepeat => ResourceManager.GetString("S_HalfRepeat", resourceCulture)!;

    public static string S_ClearRecord => ResourceManager.GetString("S_ClearRecord", resourceCulture)!;

    public static string S_SettingsCategories => ResourceManager.GetString("S_SettingsCategories", resourceCulture)!;

    public static string S_Theme => ResourceManager.GetString("S_Theme", resourceCulture)!;

    public static string S_Version => ResourceManager.GetString("S_Version", resourceCulture)!;

    public static string O_Count => ResourceManager.GetString("O_Count", resourceCulture)!;

    public static string O_Cleared => ResourceManager.GetString("O_Cleared", resourceCulture)!;

    public static string O_Fair => ResourceManager.GetString("O_Fair", resourceCulture)!;

    public static string O_HalfRepeat => ResourceManager.GetString("O_HalfRepeat", resourceCulture)!;

    public static string O_NoRepeat => ResourceManager.GetString("O_NoRepeat", resourceCulture)!;

    public static string O_Pan => ResourceManager.GetString("O_Pan", resourceCulture)!;

    public static string O_Random => ResourceManager.GetString("O_Random", resourceCulture)!;

    public static string O_Repeat => ResourceManager.GetString("O_Repeat", resourceCulture)!;

    public static string O_Restarted => ResourceManager.GetString("O_Restarted", resourceCulture)!;

    public static string O_ThemeAuto => ResourceManager.GetString("O_ThemeAuto", resourceCulture)!;

    public static string O_ThemeDark => ResourceManager.GetString("O_ThemeDark", resourceCulture)!;

    public static string O_ThemeLight => ResourceManager.GetString("O_ThemeLight", resourceCulture)!;

    public static string W_PrizeId => ResourceManager.GetString("W_PrizeId", resourceCulture)!;

    public static string W_PrizeName => ResourceManager.GetString("W_PrizeName", resourceCulture)!;

    public static string W_StudentId => ResourceManager.GetString("W_StudentId", resourceCulture)!;

    public static string W_StudentName => ResourceManager.GetString("W_StudentName", resourceCulture)!;

    public static string M_Drawing => ResourceManager.GetString("M_Drawing", resourceCulture)!;

    public static string C_GoToDraw => ResourceManager.GetString("C_GoToDraw", resourceCulture)!;

    public static string M_NoHistoryPrompt => ResourceManager.GetString("M_NoHistoryPrompt", resourceCulture)!;

    public static string M_TimeJustNow => ResourceManager.GetString("M_TimeJustNow", resourceCulture)!;

    public static string M_TimeMinutesAgo => ResourceManager.GetString("M_TimeMinutesAgo", resourceCulture)!;

    public static string M_TimeHoursAgo => ResourceManager.GetString("M_TimeHoursAgo", resourceCulture)!;

    public static string M_TimeDaysAgo => ResourceManager.GetString("M_TimeDaysAgo", resourceCulture)!;

    public static string M_Unknown => ResourceManager.GetString("M_Unknown", resourceCulture)!;

    public static string S_OnlineStatus => ResourceManager.GetString("S_OnlineStatus", resourceCulture)!;

    public static string O_Off => ResourceManager.GetString("O_Off", resourceCulture)!;

    public static string O_Anonymous => ResourceManager.GetString("O_Anonymous", resourceCulture)!;

    public static string O_Full => ResourceManager.GetString("O_Full", resourceCulture)!;

    public static string S_Telemetry => ResourceManager.GetString("S_Telemetry", resourceCulture)!;

    public static string S_SentryTelemetry => ResourceManager.GetString("S_SentryTelemetry", resourceCulture)!;

    public static string S_SentryTelemetry_D => ResourceManager.GetString("S_SentryTelemetry_D", resourceCulture)!;

    public static string S_Language => ResourceManager.GetString("S_Language", resourceCulture)!;

    public static string S_Language_D => ResourceManager.GetString("S_Language_D", resourceCulture)!;

    public static string S_GroupPreferences => ResourceManager.GetString("S_GroupPreferences", resourceCulture)!;

    public static string S_GroupData => ResourceManager.GetString("S_GroupData", resourceCulture)!;

    public static string S_GroupApp => ResourceManager.GetString("S_GroupApp", resourceCulture)!;

    public static string M_EmptyStudentList => ResourceManager.GetString("M_EmptyStudentList", resourceCulture)!;

    public static string M_EmptyStudentListHint => ResourceManager.GetString("M_EmptyStudentListHint", resourceCulture)!;

    public static string M_EmptyPrizePool => ResourceManager.GetString("M_EmptyPrizePool", resourceCulture)!;

    public static string M_EmptyPrizePoolHint => ResourceManager.GetString("M_EmptyPrizePoolHint", resourceCulture)!;

    public static string C_ExportAllData => ResourceManager.GetString("C_ExportAllData", resourceCulture)!;

    public static string C_ImportAllData => ResourceManager.GetString("C_ImportAllData", resourceCulture)!;

    public static string C_ExportSettings => ResourceManager.GetString("C_ExportSettings", resourceCulture)!;

    public static string C_ImportSettings => ResourceManager.GetString("C_ImportSettings", resourceCulture)!;

    public static string M_BackupPickerHint => ResourceManager.GetString("M_BackupPickerHint", resourceCulture)!;

    public static string S_AllData => ResourceManager.GetString("S_AllData", resourceCulture)!;

    public static string S_AllData_D => ResourceManager.GetString("S_AllData_D", resourceCulture)!;

    public static string S_SettingsSection => ResourceManager.GetString("S_SettingsSection", resourceCulture)!;

    public static string S_SettingsSection_D => ResourceManager.GetString("S_SettingsSection_D", resourceCulture)!;

    public static string M_ExportingAllData => ResourceManager.GetString("M_ExportingAllData", resourceCulture)!;

    public static string M_SaveAllDataTitle => ResourceManager.GetString("M_SaveAllDataTitle", resourceCulture)!;

    public static string M_DataArchiveFileType => ResourceManager.GetString("M_DataArchiveFileType", resourceCulture)!;

    public static string M_ExportCancelled => ResourceManager.GetString("M_ExportCancelled", resourceCulture)!;

    public static string M_WritingToTarget => ResourceManager.GetString("M_WritingToTarget", resourceCulture)!;

    public static string M_AllDataExported => ResourceManager.GetString("M_AllDataExported", resourceCulture)!;

    public static string M_ExportFailed => ResourceManager.GetString("M_ExportFailed", resourceCulture)!;

    public static string M_ExportingSettings => ResourceManager.GetString("M_ExportingSettings", resourceCulture)!;

    public static string M_SaveSettingsTitle => ResourceManager.GetString("M_SaveSettingsTitle", resourceCulture)!;

    public static string M_SettingsFileType => ResourceManager.GetString("M_SettingsFileType", resourceCulture)!;

    public static string M_SettingsExported => ResourceManager.GetString("M_SettingsExported", resourceCulture)!;

    public static string M_PickingBackupFile => ResourceManager.GetString("M_PickingBackupFile", resourceCulture)!;

    public static string M_PickAllDataTitle => ResourceManager.GetString("M_PickAllDataTitle", resourceCulture)!;

    public static string M_PickSettingsTitle => ResourceManager.GetString("M_PickSettingsTitle", resourceCulture)!;

    public static string M_ImportCancelled => ResourceManager.GetString("M_ImportCancelled", resourceCulture)!;

    public static string M_ReadingBackup => ResourceManager.GetString("M_ReadingBackup", resourceCulture)!;

    public static string M_ValidatingBackup => ResourceManager.GetString("M_ValidatingBackup", resourceCulture)!;

    public static string M_ValidationPassed => ResourceManager.GetString("M_ValidationPassed", resourceCulture)!;

    public static string M_ValidationUnsupported => ResourceManager.GetString("M_ValidationUnsupported", resourceCulture)!;

    public static string M_ReadOrValidateFailed => ResourceManager.GetString("M_ReadOrValidateFailed", resourceCulture)!;

    public static string M_SourceVersion => ResourceManager.GetString("M_SourceVersion", resourceCulture)!;

    public static string M_UnrecognizedVersion => ResourceManager.GetString("M_UnrecognizedVersion", resourceCulture)!;

    public static string M_ImportFileCount => ResourceManager.GetString("M_ImportFileCount", resourceCulture)!;

    public static string S_ConfirmImport => ResourceManager.GetString("S_ConfirmImport", resourceCulture)!;

    public static string C_ConfirmImport => ResourceManager.GetString("C_ConfirmImport", resourceCulture)!;

    public static string C_Cancel => ResourceManager.GetString("C_Cancel", resourceCulture)!;

    public static string M_BackupServiceUnavailable => ResourceManager.GetString("M_BackupServiceUnavailable", resourceCulture)!;

    public static string M_Importing => ResourceManager.GetString("M_Importing", resourceCulture)!;

    public static string M_ImportCompleted => ResourceManager.GetString("M_ImportCompleted", resourceCulture)!;

    public static string M_ImportFailed => ResourceManager.GetString("M_ImportFailed", resourceCulture)!;

    public static string M_PendingImportExists => ResourceManager.GetString("M_PendingImportExists", resourceCulture)!;

    public static string M_StorageUnavailable => ResourceManager.GetString("M_StorageUnavailable", resourceCulture)!;

    public static string C_ViewOnGitHub => ResourceManager.GetString("C_ViewOnGitHub", resourceCulture)!;

    public static string M_BrowserUnavailable => ResourceManager.GetString("M_BrowserUnavailable", resourceCulture)!;

    public static string M_OpenBrowserFailed => ResourceManager.GetString("M_OpenBrowserFailed", resourceCulture)!;

    public static string M_InAppUpdateUnsupported => ResourceManager.GetString("M_InAppUpdateUnsupported", resourceCulture)!;

    public static string M_IosUpdateDeferred => ResourceManager.GetString("M_IosUpdateDeferred", resourceCulture)!;

    public static string M_UpdateSecurityNote => ResourceManager.GetString("M_UpdateSecurityNote", resourceCulture)!;
}
