//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.MainPages.History {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.MainPages.History.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Page_Title => ResourceManager.GetString("Page_Title", resourceCulture);
        public static string Tab_RollCall => ResourceManager.GetString("Tab_RollCall", resourceCulture);
        public static string Tab_Lottery => ResourceManager.GetString("Tab_Lottery", resourceCulture);
        public static string C_SelectClass => ResourceManager.GetString("C_SelectClass", resourceCulture);
        public static string C_SelectPool => ResourceManager.GetString("C_SelectPool", resourceCulture);
        public static string C_SelectMode => ResourceManager.GetString("C_SelectMode", resourceCulture);
        public static string C_Refresh => ResourceManager.GetString("C_Refresh", resourceCulture);
        public static string C_ModeOverview => ResourceManager.GetString("C_ModeOverview", resourceCulture);
        public static string C_ModeRecords => ResourceManager.GetString("C_ModeRecords", resourceCulture);
        public static string C_MethodRandom => ResourceManager.GetString("C_MethodRandom", resourceCulture);
        public static string C_MethodWeight => ResourceManager.GetString("C_MethodWeight", resourceCulture);
        public static string C_NoData => ResourceManager.GetString("C_NoData", resourceCulture);
        public static string H_Name => ResourceManager.GetString("H_Name", resourceCulture);
        public static string H_PrizeName => ResourceManager.GetString("H_PrizeName", resourceCulture);
        public static string H_TotalCountRollCall => ResourceManager.GetString("H_TotalCountRollCall", resourceCulture);
        public static string H_TotalCountLottery => ResourceManager.GetString("H_TotalCountLottery", resourceCulture);
        public static string H_DrawTime => ResourceManager.GetString("H_DrawTime", resourceCulture);
        public static string H_LotteryTime => ResourceManager.GetString("H_LotteryTime", resourceCulture);
        public static string H_DrawMode => ResourceManager.GetString("H_DrawMode", resourceCulture);
        public static string H_DrawNumbers => ResourceManager.GetString("H_DrawNumbers", resourceCulture);
        public static string H_LotteryNumbers => ResourceManager.GetString("H_LotteryNumbers", resourceCulture);
        public static string H_GenderLimit => ResourceManager.GetString("H_GenderLimit", resourceCulture);
        public static string H_GroupLimit => ResourceManager.GetString("H_GroupLimit", resourceCulture);
        public static string H_Gender => ResourceManager.GetString("H_Gender", resourceCulture);
        public static string H_Group => ResourceManager.GetString("H_Group", resourceCulture);
        public static string H_StudentId => ResourceManager.GetString("H_StudentId", resourceCulture);
        public static string H_Serial => ResourceManager.GetString("H_Serial", resourceCulture);
        public static string H_Weight => ResourceManager.GetString("H_Weight", resourceCulture);
    }
}
