//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Basic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Basic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题管理.
        /// </summary>
        public static string C_ThemeManager {
            get {
                return ResourceManager.GetString("C_ThemeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开主题管理与背景设置.
        /// </summary>
        public static string C_ThemeManager_D {
            get {
                return ResourceManager.GetString("C_ThemeManager_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本公告.
        /// </summary>
        public static string C_VersionNotice {
            get {
                return ResourceManager.GetString("C_VersionNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不再显示.
        /// </summary>
        public static string C_VersionNoticeHide {
            get {
                return ResourceManager.GetString("C_VersionNoticeHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前处于 Avalonia 重构阶段，暂不新增功能，重心放在性能优化与问题修复。
        ///敬请期待基于 Avalonia 架构的 v3 版本！
        ///bug 报 GitHub Issue 或 SECTL QQ组织群 - 833875216.
        /// </summary>
        public static string C_VersionNoticeText {
            get {
                return ResourceManager.GetString("C_VersionNoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiSans (默认).
        /// </summary>
        public static string O_FontFamily_Default {
            get {
                return ResourceManager.GetString("O_FontFamily_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极粗.
        /// </summary>
        public static string O_FontWeight_Black {
            get {
                return ResourceManager.GetString("O_FontWeight_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粗体.
        /// </summary>
        public static string O_FontWeight_Bold {
            get {
                return ResourceManager.GetString("O_FontWeight_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特粗.
        /// </summary>
        public static string O_FontWeight_ExtraBold {
            get {
                return ResourceManager.GetString("O_FontWeight_ExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特细.
        /// </summary>
        public static string O_FontWeight_ExtraLight {
            get {
                return ResourceManager.GetString("O_FontWeight_ExtraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 细体.
        /// </summary>
        public static string O_FontWeight_Light {
            get {
                return ResourceManager.GetString("O_FontWeight_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中等.
        /// </summary>
        public static string O_FontWeight_Medium {
            get {
                return ResourceManager.GetString("O_FontWeight_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        public static string O_FontWeight_Regular {
            get {
                return ResourceManager.GetString("O_FontWeight_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半粗.
        /// </summary>
        public static string O_FontWeight_SemiBold {
            get {
                return ResourceManager.GetString("O_FontWeight_SemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极细.
        /// </summary>
        public static string O_FontWeight_Thin {
            get {
                return ResourceManager.GetString("O_FontWeight_Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭置顶.
        /// </summary>
        public static string O_MainWindowTopmostMode_None {
            get {
                return ResourceManager.GetString("O_MainWindowTopmostMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置顶.
        /// </summary>
        public static string O_MainWindowTopmostMode_Topmost {
            get {
                return ResourceManager.GetString("O_MainWindowTopmostMode_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIAccess 置顶.
        /// </summary>
        public static string O_MainWindowTopmostMode_UiAccess {
            get {
                return ResourceManager.GetString("O_MainWindowTopmostMode_UiAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匿名上报.
        /// </summary>
        public static string O_TelemetryMode_Anonymous {
            get {
                return ResourceManager.GetString("O_TelemetryMode_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完整上报.
        /// </summary>
        public static string O_TelemetryMode_Full {
            get {
                return ResourceManager.GetString("O_TelemetryMode_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止上报.
        /// </summary>
        public static string O_TelemetryMode_Off {
            get {
                return ResourceManager.GetString("O_TelemetryMode_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string O_Theme_Auto {
            get {
                return ResourceManager.GetString("O_Theme_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string O_Theme_Dark {
            get {
                return ResourceManager.GetString("O_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string O_Theme_Light {
            get {
                return ResourceManager.GetString("O_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行为.
        /// </summary>
        public static string S_Behavior {
            get {
                return ResourceManager.GetString("S_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动保存窗口大小.
        /// </summary>
        public static string S_Behavior_AutoSaveWindowSize {
            get {
                return ResourceManager.GetString("S_Behavior_AutoSaveWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否自动保存窗口大小.
        /// </summary>
        public static string S_Behavior_AutoSaveWindowSize_D {
            get {
                return ResourceManager.GetString("S_Behavior_AutoSaveWindowSize_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开机自启.
        /// </summary>
        public static string S_Behavior_Autostart {
            get {
                return ResourceManager.GetString("S_Behavior_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件是否随系统启动自动运行.
        /// </summary>
        public static string S_Behavior_Autostart_D {
            get {
                return ResourceManager.GetString("S_Behavior_Autostart_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台驻留.
        /// </summary>
        public static string S_Behavior_BackgroundResident {
            get {
                return ResourceManager.GetString("S_Behavior_BackgroundResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭所有窗口后是否仍在后台常驻.
        /// </summary>
        public static string S_Behavior_BackgroundResident_D {
            get {
                return ResourceManager.GetString("S_Behavior_BackgroundResident_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主窗口置顶模式.
        /// </summary>
        public static string S_Behavior_MainWindowTopmostMode {
            get {
                return ResourceManager.GetString("S_Behavior_MainWindowTopmostMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择主窗口置顶方式（UIAccess 置顶需以管理员运行）.
        /// </summary>
        public static string S_Behavior_MainWindowTopmostMode_D {
            get {
                return ResourceManager.GetString("S_Behavior_MainWindowTopmostMode_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动显示主窗口.
        /// </summary>
        public static string S_Behavior_ShowStartupWindow {
            get {
                return ResourceManager.GetString("S_Behavior_ShowStartupWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件启动时是否自动显示主窗口.
        /// </summary>
        public static string S_Behavior_ShowStartupWindow_D {
            get {
                return ResourceManager.GetString("S_Behavior_ShowStartupWindow_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL 协议注册 &amp; IPC 服务.
        /// </summary>
        public static string S_Behavior_UrlProtocol {
            get {
                return ResourceManager.GetString("S_Behavior_UrlProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册自定义 URL 协议 (secrandom://)，并启用 IPC 通信，支持链接启动与外部联动.
        /// </summary>
        public static string S_Behavior_UrlProtocol_D {
            get {
                return ResourceManager.GetString("S_Behavior_UrlProtocol_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据管理.
        /// </summary>
        public static string S_DataManagement {
            get {
                return ResourceManager.GetString("S_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份管理.
        /// </summary>
        public static string S_DataManagement_BackupManager {
            get {
                return ResourceManager.GetString("S_DataManagement_BackupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理自动备份与手动备份.
        /// </summary>
        public static string S_DataManagement_BackupManager_D {
            get {
                return ResourceManager.GetString("S_DataManagement_BackupManager_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出所有数据.
        /// </summary>
        public static string S_DataManagement_ExportAllData {
            get {
                return ResourceManager.GetString("S_DataManagement_ExportAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出软件时导出全部数据和设置.
        /// </summary>
        public static string S_DataManagement_ExportAllData_D {
            get {
                return ResourceManager.GetString("S_DataManagement_ExportAllData_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出诊断数据.
        /// </summary>
        public static string S_DataManagement_ExportDiagnosticData {
            get {
                return ResourceManager.GetString("S_DataManagement_ExportDiagnosticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出软件时导出诊断信息，用于排查问题.
        /// </summary>
        public static string S_DataManagement_ExportDiagnosticData_D {
            get {
                return ResourceManager.GetString("S_DataManagement_ExportDiagnosticData_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出设置.
        /// </summary>
        public static string S_DataManagement_ExportSettings {
            get {
                return ResourceManager.GetString("S_DataManagement_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将当前设置导出为配置文件，用于备份和迁移.
        /// </summary>
        public static string S_DataManagement_ExportSettings_D {
            get {
                return ResourceManager.GetString("S_DataManagement_ExportSettings_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入所有数据.
        /// </summary>
        public static string S_DataManagement_ImportAllData {
            get {
                return ResourceManager.GetString("S_DataManagement_ImportAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动软件时从备份文件恢复全部数据.
        /// </summary>
        public static string S_DataManagement_ImportAllData_D {
            get {
                return ResourceManager.GetString("S_DataManagement_ImportAllData_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入设置.
        /// </summary>
        public static string S_DataManagement_ImportSettings {
            get {
                return ResourceManager.GetString("S_DataManagement_ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从配置文件导入设置，覆盖当前配置信息.
        /// </summary>
        public static string S_DataManagement_ImportSettings_D {
            get {
                return ResourceManager.GetString("S_DataManagement_ImportSettings_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看日志.
        /// </summary>
        public static string S_DataManagement_LogViewer {
            get {
                return ResourceManager.GetString("S_DataManagement_LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看和管理程序日志文件.
        /// </summary>
        public static string S_DataManagement_LogViewer_D {
            get {
                return ResourceManager.GetString("S_DataManagement_LogViewer_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个性化.
        /// </summary>
        public static string S_Personalized {
            get {
                return ResourceManager.GetString("S_Personalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体.
        /// </summary>
        public static string S_Personalized_Font {
            get {
                return ResourceManager.GetString("S_Personalized_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件界面显示字体.
        /// </summary>
        public static string S_Personalized_Font_D {
            get {
                return ResourceManager.GetString("S_Personalized_Font_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体粗细.
        /// </summary>
        public static string S_Personalized_FontWeight {
            get {
                return ResourceManager.GetString("S_Personalized_FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件界面字体粗细.
        /// </summary>
        public static string S_Personalized_FontWeight_D {
            get {
                return ResourceManager.GetString("S_Personalized_FontWeight_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示语言.
        /// </summary>
        public static string S_Personalized_Language {
            get {
                return ResourceManager.GetString("S_Personalized_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换软件界面语言（重启软件后生效）.
        /// </summary>
        public static string S_Personalized_Language_D {
            get {
                return ResourceManager.GetString("S_Personalized_Language_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题模式.
        /// </summary>
        public static string S_Personalized_Theme {
            get {
                return ResourceManager.GetString("S_Personalized_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择软件界面主题样式.
        /// </summary>
        public static string S_Personalized_Theme_D {
            get {
                return ResourceManager.GetString("S_Personalized_Theme_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题颜色.
        /// </summary>
        public static string S_Personalized_ThemeColor {
            get {
                return ResourceManager.GetString("S_Personalized_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件界面主题色彩.
        /// </summary>
        public static string S_Personalized_ThemeColor_D {
            get {
                return ResourceManager.GetString("S_Personalized_ThemeColor_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遥测.
        /// </summary>
        public static string S_Telemetry {
            get {
                return ResourceManager.GetString("S_Telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用遥测.
        /// </summary>
        public static string S_Telemetry_Enabled {
            get {
                return ResourceManager.GetString("S_Telemetry_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启后上报在线状态数据以帮助改进软件.
        /// </summary>
        public static string S_Telemetry_Enabled_D {
            get {
                return ResourceManager.GetString("S_Telemetry_Enabled_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线状态.
        /// </summary>
        public static string S_Telemetry_Mode {
            get {
                return ResourceManager.GetString("S_Telemetry_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完整上报含位置信息，匿名上报仅计入在线人数不报位置，停止则不上报.
        /// </summary>
        public static string S_Telemetry_Mode_D {
            get {
                return ResourceManager.GetString("S_Telemetry_Mode_D", resourceCulture);
            }
        }
    }
}
