// <auto-generated />
using System.Globalization;
using System.Resources;

namespace SecRandom.Langs.SettingsPages.Picking;

public class Resources
{
    private static readonly ResourceManager ResourceManagerValue = new(
        "SecRandom.Langs.SettingsPages.Picking.Resources", typeof(Resources).Assembly);

    private static CultureInfo resourceCulture;

    public static CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static ResourceManager ResourceManager => ResourceManagerValue;

    private static string Get(string name) => ResourceManager.GetString(name, resourceCulture) ?? name;

    public static string Page_Default => Get(nameof(Page_Default));
    public static string Page_RollCall => Get(nameof(Page_RollCall));
    public static string Page_QuickDraw => Get(nameof(Page_QuickDraw));
    public static string Page_Lottery => Get(nameof(Page_Lottery));
    public static string Section_Draw => Get(nameof(Section_Draw));
    public static string Section_Display => Get(nameof(Section_Display));
    public static string Section_Animation => Get(nameof(Section_Animation));
    public static string Section_Color => Get(nameof(Section_Color));
    public static string Section_StudentImage => Get(nameof(Section_StudentImage));
    public static string Section_Reminder => Get(nameof(Section_Reminder));
    public static string C_EnableOverride => Get(nameof(C_EnableOverride));
    public static string S_DrawMode => Get(nameof(S_DrawMode));
    public static string S_DrawMode_D => Get(nameof(S_DrawMode_D));
    public static string S_HalfRepeat => Get(nameof(S_HalfRepeat));
    public static string S_HalfRepeat_D => Get(nameof(S_HalfRepeat_D));
    public static string S_ClearRecord => Get(nameof(S_ClearRecord));
    public static string S_ClearRecord_D => Get(nameof(S_ClearRecord_D));
    public static string S_DrawType => Get(nameof(S_DrawType));
    public static string S_DrawType_D => Get(nameof(S_DrawType_D));
    public static string S_LotteryDrawType => Get(nameof(S_LotteryDrawType));
    public static string S_LotteryDrawType_D => Get(nameof(S_LotteryDrawType_D));
    public static string S_DefaultClass => Get(nameof(S_DefaultClass));
    public static string S_DefaultClass_D => Get(nameof(S_DefaultClass_D));
    public static string S_DefaultPool => Get(nameof(S_DefaultPool));
    public static string S_DefaultPool_D => Get(nameof(S_DefaultPool_D));
    public static string S_DrawCount => Get(nameof(S_DrawCount));
    public static string S_DrawCount_D => Get(nameof(S_DrawCount_D));
    public static string S_DisableAfterClick => Get(nameof(S_DisableAfterClick));
    public static string S_DisableAfterClick_D => Get(nameof(S_DisableAfterClick_D));
    public static string S_FontSource => Get(nameof(S_FontSource));
    public static string S_FontSource_D => Get(nameof(S_FontSource_D));
    public static string S_CustomFont => Get(nameof(S_CustomFont));
    public static string S_CustomFont_D => Get(nameof(S_CustomFont_D));
    public static string S_FontSize => Get(nameof(S_FontSize));
    public static string S_FontSize_D => Get(nameof(S_FontSize_D));
    public static string S_DisplayFormat => Get(nameof(S_DisplayFormat));
    public static string S_DisplayFormat_D => Get(nameof(S_DisplayFormat_D));
    public static string S_DisplayStyle => Get(nameof(S_DisplayStyle));
    public static string S_DisplayStyle_D => Get(nameof(S_DisplayStyle_D));
    public static string S_ShowRandom => Get(nameof(S_ShowRandom));
    public static string S_ShowRandom_D => Get(nameof(S_ShowRandom_D));
    public static string S_LotteryShowRandom => Get(nameof(S_LotteryShowRandom));
    public static string S_LotteryShowRandom_D => Get(nameof(S_LotteryShowRandom_D));
    public static string S_ShowTags => Get(nameof(S_ShowTags));
    public static string S_ShowTags_D => Get(nameof(S_ShowTags_D));
    public static string S_ShowWeightTransparency => Get(nameof(S_ShowWeightTransparency));
    public static string S_ShowWeightTransparency_D => Get(nameof(S_ShowWeightTransparency_D));
    public static string S_ReminderText => Get(nameof(S_ReminderText));
    public static string S_ReminderText_D => Get(nameof(S_ReminderText_D));
    public static string S_ReminderFontSize => Get(nameof(S_ReminderFontSize));
    public static string S_ReminderFontSize_D => Get(nameof(S_ReminderFontSize_D));
    public static string S_ReminderTextColor => Get(nameof(S_ReminderTextColor));
    public static string S_ReminderTextColor_D => Get(nameof(S_ReminderTextColor_D));
    public static string S_ReminderTextOpacity => Get(nameof(S_ReminderTextOpacity));
    public static string S_ReminderTextOpacity_D => Get(nameof(S_ReminderTextOpacity_D));
    public static string S_Animation => Get(nameof(S_Animation));
    public static string S_Animation_D => Get(nameof(S_Animation_D));
    public static string S_AnimationInterval => Get(nameof(S_AnimationInterval));
    public static string S_AnimationInterval_D => Get(nameof(S_AnimationInterval_D));
    public static string S_AutoplayCount => Get(nameof(S_AutoplayCount));
    public static string S_AutoplayCount_D => Get(nameof(S_AutoplayCount_D));
    public static string S_ResultFlowAnimationStyle => Get(nameof(S_ResultFlowAnimationStyle));
    public static string S_ResultFlowAnimationStyle_D => Get(nameof(S_ResultFlowAnimationStyle_D));
    public static string S_ResultFlowAnimationDuration => Get(nameof(S_ResultFlowAnimationDuration));
    public static string S_ResultFlowAnimationDuration_D => Get(nameof(S_ResultFlowAnimationDuration_D));
    public static string S_ColorTheme => Get(nameof(S_ColorTheme));
    public static string S_ColorTheme_D => Get(nameof(S_ColorTheme_D));
    public static string S_FixedColor => Get(nameof(S_FixedColor));
    public static string S_FixedColor_D => Get(nameof(S_FixedColor_D));
    public static string S_StudentImage => Get(nameof(S_StudentImage));
    public static string S_StudentImage_D => Get(nameof(S_StudentImage_D));
    public static string S_StudentImagePosition => Get(nameof(S_StudentImagePosition));
    public static string S_StudentImagePosition_D => Get(nameof(S_StudentImagePosition_D));
    public static string O_Repeat => Get(nameof(O_Repeat));
    public static string O_NoRepeat => Get(nameof(O_NoRepeat));
    public static string O_HalfRepeat => Get(nameof(O_HalfRepeat));
    public static string O_Restarted => Get(nameof(O_Restarted));
    public static string O_Cleared => Get(nameof(O_Cleared));
    public static string O_Random => Get(nameof(O_Random));
    public static string O_Fair => Get(nameof(O_Fair));
    public static string O_Pan => Get(nameof(O_Pan));
    public static string O_Count => Get(nameof(O_Count));
    public static string O_FollowGlobal => Get(nameof(O_FollowGlobal));
    public static string O_Custom => Get(nameof(O_Custom));
    public static string O_Both => Get(nameof(O_Both));
    public static string O_Name => Get(nameof(O_Name));
    public static string O_Id => Get(nameof(O_Id));
    public static string O_Default => Get(nameof(O_Default));
    public static string O_Card => Get(nameof(O_Card));
    public static string O_None => Get(nameof(O_None));
    public static string O_BreakLine => Get(nameof(O_BreakLine));
    public static string O_Hyphen => Get(nameof(O_Hyphen));
    public static string O_ManualStop => Get(nameof(O_ManualStop));
    public static string O_AutoPlay => Get(nameof(O_AutoPlay));
    public static string O_NoAnimation => Get(nameof(O_NoAnimation));
    public static string O_NoColor => Get(nameof(O_NoColor));
    public static string O_RandomColor => Get(nameof(O_RandomColor));
    public static string O_FixedColor => Get(nameof(O_FixedColor));
    public static string O_Left => Get(nameof(O_Left));
    public static string O_Top => Get(nameof(O_Top));
    public static string O_Right => Get(nameof(O_Right));
    public static string O_Bottom => Get(nameof(O_Bottom));
    public static string O_PrizeBreakGroupHyphenName => Get(nameof(O_PrizeBreakGroupHyphenName));
    public static string O_PrizeBreakGroupBreakName => Get(nameof(O_PrizeBreakGroupBreakName));
    public static string O_PrizeHyphenGroupHyphenName => Get(nameof(O_PrizeHyphenGroupHyphenName));
    public static string O_PrizeBreakName => Get(nameof(O_PrizeBreakName));
    public static string O_PrizeHyphenName => Get(nameof(O_PrizeHyphenName));
    public static string O_PrizeBreakGroup => Get(nameof(O_PrizeBreakGroup));
    public static string O_PrizeHyphenGroup => Get(nameof(O_PrizeHyphenGroup));
}
