//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SecRandom.Mobile.Langs.Mobile;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute(
    "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal Resources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager =>
        resourceMan ??= new global::System.Resources.ResourceManager(
            "SecRandom.Mobile.Langs.Mobile.Resources", typeof(Resources).Assembly);

    [global::System.ComponentModel.EditorBrowsableAttribute(
        global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string Description => ResourceManager.GetString("Description", resourceCulture)!;

    public static string CheckUpdates => ResourceManager.GetString("CheckUpdates", resourceCulture)!;

    public static string InstallUpdate => ResourceManager.GetString("InstallUpdate", resourceCulture)!;

    public static string PlatformSummary => ResourceManager.GetString("PlatformSummary", resourceCulture)!;

    public static string Subtitle => ResourceManager.GetString("Subtitle", resourceCulture)!;

    public static string Title => ResourceManager.GetString("Title", resourceCulture)!;
}
