//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the resource designer.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SecRandom.Langs.SettingsPages.Personalized.Music;

using System.Globalization;
using System.Resources;

public class Resources
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    public static ResourceManager ResourceManager => resourceMan ??= new ResourceManager(
        "SecRandom.Langs.SettingsPages.Personalized.Music.Resources", typeof(Resources).Assembly);

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string Page_Title => Get(nameof(Page_Title));
    public static string S_Library => Get(nameof(S_Library));
    public static string S_Library_D => Get(nameof(S_Library_D));
    public static string C_Import => Get(nameof(C_Import));
    public static string C_FileName => Get(nameof(C_FileName));
    public static string C_Format => Get(nameof(C_Format));
    public static string C_Size => Get(nameof(C_Size));
    public static string C_Operations => Get(nameof(C_Operations));
    public static string C_Preview => Get(nameof(C_Preview));
    public static string C_Stop => Get(nameof(C_Stop));
    public static string C_Cancel => Get(nameof(C_Cancel));
    public static string C_Delete => Get(nameof(C_Delete));
    public static string M_Empty => Get(nameof(M_Empty));
    public static string M_ImportFailed => Get(nameof(M_ImportFailed));
    public static string M_PreviewFailed => Get(nameof(M_PreviewFailed));
    public static string M_DeleteTitle => Get(nameof(M_DeleteTitle));
    public static string M_DeleteContent => Get(nameof(M_DeleteContent));
    public static string M_DeletePrimary => Get(nameof(M_DeletePrimary));
    public static string M_DeleteFailed => Get(nameof(M_DeleteFailed));
    public static string M_DeleteSuccess => Get(nameof(M_DeleteSuccess));
    public static string M_Imported => Get(nameof(M_Imported));

    private static string Get(string name) => ResourceManager.GetString(name, resourceCulture) ?? name;
}
