using System;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SecRandom.FluentIconMappingGenerator;

[Generator]
public class FluentIconMappingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFileProvider = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, _) =>
            {
                var (additionalFile, optionsProvider) = pair;
                var fileOptions = optionsProvider.GetOptions(additionalFile);

                fileOptions.TryGetValue("build_property.FluentIconMappingNamespace", out var ns);
                fileOptions.TryGetValue("build_property.FluentIconMappingClassName", out var className);
                fileOptions.TryGetValue("build_property.FluentIconMappingFile", out var filePath);

                return new
                {
                    File = additionalFile,
                    Options = new MappingOptions(
                        Namespace: ns ?? "FluentIcon",
                        ClassName: className ?? "Mapping",
                        RelativePath: filePath ?? "")
                };
            })
            .Where(tuple =>
            {
                if (string.IsNullOrWhiteSpace(tuple.Options.RelativePath) ||
                    string.IsNullOrWhiteSpace(tuple.File.Path))
                    return false;

                var expectedNorm = tuple.Options.RelativePath.Replace('\\', '/');
                var actualNorm = tuple.File.Path.Replace('\\', '/');
                return actualNorm.EndsWith(expectedNorm, StringComparison.OrdinalIgnoreCase);
            });

        context.RegisterSourceOutput(jsonFileProvider, (spc, input) =>
        {
            var additionalFile = input.File;
            var options = input.Options;

            var sourceText = additionalFile.GetText();
            if (sourceText == null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "FMG001",
                        "Cannot read mapping file",
                        "无法读取图标映射文件 '{0}'",
                        "FluentIconMappingGenerator",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None,
                    additionalFile.Path));
                return;
            }

            var jsonContent = sourceText.ToString();
            var generatedCode = GenerateMappingClass(options.Namespace, options.ClassName, jsonContent);
            spc.AddSource($"{options.ClassName}.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
        });
    }

    private string GenerateMappingClass(string namespaceName, string className, string jsonContent)
    {
        using var document = JsonDocument.Parse(jsonContent);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {className}");
        sb.AppendLine("    {");

        foreach (var property in document.RootElement.EnumerateObject())
        {
            var name = property.Name.Replace("ic_fluent_", "").Replace("_20_", "_");
            var value = property.Value.GetInt32();
            sb.AppendLine($"        public static string {name} => \"\\u{value:X4}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record MappingOptions(string Namespace, string ClassName, string RelativePath)
    {
        public string Namespace { get; } = Namespace;
        public string ClassName { get; } = ClassName;
        public string RelativePath { get; } = RelativePath;
    }
}
