using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SecRandom.FluentIconMappingGenerator;

[Generator]
public class FluentIconMappingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jsonFileProvider = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select((pair, _) =>
            {
                var (additionalFile, optionsProvider) = pair;
                var fileOptions = optionsProvider.GetOptions(additionalFile);

                fileOptions.TryGetValue("build_property.FluentIconMappingNamespace", out var ns);
                fileOptions.TryGetValue("build_property.FluentIconMappingClassName", out var className);
                fileOptions.TryGetValue("build_property.FluentIconMappingFile", out var filePath);

                return new
                {
                    File = additionalFile,
                    Options = new MappingOptions(
                        Namespace: ns ?? "SecRandom.Core.FluentIcons",
                        ClassName: className ?? "FI",
                        RelativePath: filePath ?? "")
                };
            })
            .Where(tuple =>
            {
                if (string.IsNullOrWhiteSpace(tuple.Options.RelativePath) ||
                    string.IsNullOrWhiteSpace(tuple.File.Path))
                    return false;

                var expectedNorm = tuple.Options.RelativePath.Replace('\\', '/');
                var actualNorm = tuple.File.Path.Replace('\\', '/');
                return actualNorm.EndsWith(expectedNorm, StringComparison.OrdinalIgnoreCase);
            });

        context.RegisterSourceOutput(jsonFileProvider, (spc, input) =>
        {
            var additionalFile = input.File;
            var options = input.Options;

            var sourceText = additionalFile.GetText();
            if (sourceText == null)
            {
                // 报告错误略...
                return;
            }

            var jsonContent = sourceText.ToString();
            var icons = ParseIcons(jsonContent); // 解析 JSON 得到 (name, unicodeCodePoint) 列表

            // 1. 生成原来的 FI 静态类
            var fiClassCode = GenerateFIClass(options.Namespace, options.ClassName, icons);
            spc.AddSource($"{options.ClassName}.g.cs", SourceText.From(fiClassCode, Encoding.UTF8));

            // 2. 生成 FluentIcon 枚举
            var enumCode = GenerateFluentIconEnum(options.Namespace, icons);
            spc.AddSource("FluentIcon.g.cs", SourceText.From(enumCode, Encoding.UTF8));

            // 3. 生成标记扩展 FIExtension
            var extensionCode = GenerateFIExtension(options.Namespace, options.ClassName, icons);
            spc.AddSource("FIExtension.g.cs", SourceText.From(extensionCode, Encoding.UTF8));
        });
    }

    /// <summary>解析 JSON 文件，返回 (图标名, Unicode码点) 列表</summary>
    private List<(string Name, string CodePoint)> ParseIcons(string jsonContent)
    {
        using var doc = JsonDocument.Parse(jsonContent);
        var list = new List<(string, string)>();
        foreach (var prop in doc.RootElement.EnumerateObject())
        {
            // 转换规则：ic_fluent_access_time_filled_20_regular → access_time_filled_regular
            var rawName = prop.Name;
            var name = rawName
                .Replace("ic_fluent_", "")
                .Replace("_20_", "_");
            var codePoint = prop.Value.GetInt32();
            list.Add((name, $"\\u{codePoint:X4}"));
        }
        return list;
    }

    private string GenerateFIClass(string ns, string className, List<(string Name, string CodePoint)> icons)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {className}");
        sb.AppendLine("    {");

        foreach (var (name, codePoint) in icons)
        {
            sb.AppendLine($"        public static string {name} => \"{codePoint}\";");
            sb.AppendLine($"        public const string ic_{name} = \"{codePoint}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateFluentIconEnum(string ns, List<(string Name, string CodePoint)> icons)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Fluent UI 图标枚举，用于 XAML 标记扩展</summary>");
        sb.AppendLine("    public enum FluentIcon");
        sb.AppendLine("    {");

        foreach (var (name, codePoint) in icons)
        {
            sb.AppendLine($"        {name} = {int.Parse(codePoint.Substring(2), NumberStyles.HexNumber)},");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string GenerateFIExtension(string ns, string fiClassName, List<(string Name, string CodePoint)> icons)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Avalonia.Markup.Xaml;");
        sb.AppendLine("using Avalonia.Markup.Xaml.MarkupExtensions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// XAML 标记扩展，用法: <c>{icons:FI IconName}</c>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public class FIExtension");
        sb.AppendLine("    {");
        sb.AppendLine("        public FIExtension() { }");
        sb.AppendLine();
        sb.AppendLine("        public FIExtension(FluentIcon icon) => Icon = icon;");
        sb.AppendLine();
        sb.AppendLine("        public FluentIcon Icon { get; set; }");
        sb.AppendLine();
        sb.AppendLine("        public string ProvideValue(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            int codePoint = (int)Icon;");
        sb.AppendLine("            return char.ConvertFromUtf32(codePoint);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private record MappingOptions(string Namespace, string ClassName, string RelativePath)
    {
        public string Namespace { get; } = Namespace;
        public string ClassName { get; } = ClassName;
        public string RelativePath { get; } = RelativePath;
    }
}