//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagement.LotteryList {
    using System;

    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        internal Resources() { }
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagement.LotteryList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        public static global::System.Globalization.CultureInfo Culture { get => resourceCulture; set => resourceCulture = value; }
        public static string C_AddList => ResourceManager.GetString("C_AddList", resourceCulture);
        public static string C_AddPrize => ResourceManager.GetString("C_AddPrize", resourceCulture);
        public static string C_Cancel => ResourceManager.GetString("C_Cancel", resourceCulture);
        public static string C_ColumnMapping => ResourceManager.GetString("C_ColumnMapping", resourceCulture);
        public static string C_ColumnMapping_D => ResourceManager.GetString("C_ColumnMapping_D", resourceCulture);
        public static string C_Count => ResourceManager.GetString("C_Count", resourceCulture);
        public static string C_CountColumn => ResourceManager.GetString("C_CountColumn", resourceCulture);
        public static string C_DefaultListName => ResourceManager.GetString("C_DefaultListName", resourceCulture);
        public static string C_DeleteList => ResourceManager.GetString("C_DeleteList", resourceCulture);
        public static string C_Operations => ResourceManager.GetString("C_Operations", resourceCulture);
        public static string C_DeletePrize => ResourceManager.GetString("C_DeletePrize", resourceCulture);
        public static string C_Exists => ResourceManager.GetString("C_Exists", resourceCulture);
        public static string C_FilePickerTitle => ResourceManager.GetString("C_FilePickerTitle", resourceCulture);
        public static string C_FilePickerTypeName => ResourceManager.GetString("C_FilePickerTypeName", resourceCulture);
        public static string C_Import => ResourceManager.GetString("C_Import", resourceCulture);
        public static string C_ImportList => ResourceManager.GetString("C_ImportList", resourceCulture);
        public static string C_ImportTitle => ResourceManager.GetString("C_ImportTitle", resourceCulture);
        public static string C_InfoMessage => ResourceManager.GetString("C_InfoMessage", resourceCulture);
        public static string C_InfoTitle => ResourceManager.GetString("C_InfoTitle", resourceCulture);
        public static string C_Name => ResourceManager.GetString("C_Name", resourceCulture);
        public static string C_NameColumn => ResourceManager.GetString("C_NameColumn", resourceCulture);
        public static string C_NoFileSelected => ResourceManager.GetString("C_NoFileSelected", resourceCulture);
        public static string C_NoneColumn => ResourceManager.GetString("C_NoneColumn", resourceCulture);
        public static string C_PrizeId => ResourceManager.GetString("C_PrizeId", resourceCulture);
        public static string C_PrizeIdColumn => ResourceManager.GetString("C_PrizeIdColumn", resourceCulture);
        public static string C_Refresh => ResourceManager.GetString("C_Refresh", resourceCulture);
        public static string C_RenameList => ResourceManager.GetString("C_RenameList", resourceCulture);
        public static string C_SelectFile => ResourceManager.GetString("C_SelectFile", resourceCulture);
        public static string C_SelectFileButton => ResourceManager.GetString("C_SelectFileButton", resourceCulture);
        public static string C_SupportedFormats => ResourceManager.GetString("C_SupportedFormats", resourceCulture);
        public static string C_Tags => ResourceManager.GetString("C_Tags", resourceCulture);
        public static string C_TagsColumn => ResourceManager.GetString("C_TagsColumn", resourceCulture);
        public static string C_TargetList => ResourceManager.GetString("C_TargetList", resourceCulture);
        public static string C_Weight => ResourceManager.GetString("C_Weight", resourceCulture);
        public static string C_WeightColumn => ResourceManager.GetString("C_WeightColumn", resourceCulture);
        public static string K_CountColumns => ResourceManager.GetString("K_CountColumns", resourceCulture);
        public static string K_IdColumns => ResourceManager.GetString("K_IdColumns", resourceCulture);
        public static string K_NameColumns => ResourceManager.GetString("K_NameColumns", resourceCulture);
        public static string K_TagsColumns => ResourceManager.GetString("K_TagsColumns", resourceCulture);
        public static string K_WeightColumns => ResourceManager.GetString("K_WeightColumns", resourceCulture);
        public static string M_AddListSuccess => ResourceManager.GetString("M_AddListSuccess", resourceCulture);
        public static string M_AddPrizeInvalidValues => ResourceManager.GetString("M_AddPrizeInvalidValues", resourceCulture);
        public static string M_AddPrizeRequired => ResourceManager.GetString("M_AddPrizeRequired", resourceCulture);
        public static string M_AddPrizeSuccess => ResourceManager.GetString("M_AddPrizeSuccess", resourceCulture);
        public static string M_AddPrizeTitle => ResourceManager.GetString("M_AddPrizeTitle", resourceCulture);
        public static string M_DuplicateClose => ResourceManager.GetString("M_DuplicateClose", resourceCulture);
        public static string M_DuplicateContent => ResourceManager.GetString("M_DuplicateContent", resourceCulture);
        public static string M_DuplicatePrimary => ResourceManager.GetString("M_DuplicatePrimary", resourceCulture);
        public static string M_DuplicateSecondary => ResourceManager.GetString("M_DuplicateSecondary", resourceCulture);
        public static string M_DuplicateTitle => ResourceManager.GetString("M_DuplicateTitle", resourceCulture);
        public static string M_DeleteListContent => ResourceManager.GetString("M_DeleteListContent", resourceCulture);
        public static string M_DeleteListPrimary => ResourceManager.GetString("M_DeleteListPrimary", resourceCulture);
        public static string M_DeleteListSuccess => ResourceManager.GetString("M_DeleteListSuccess", resourceCulture);
        public static string M_DeleteListTitle => ResourceManager.GetString("M_DeleteListTitle", resourceCulture);
        public static string M_DeletePrizeContent => ResourceManager.GetString("M_DeletePrizeContent", resourceCulture);
        public static string M_DeletePrizeNotFound => ResourceManager.GetString("M_DeletePrizeNotFound", resourceCulture);
        public static string M_DeletePrizePrimary => ResourceManager.GetString("M_DeletePrizePrimary", resourceCulture);
        public static string M_DeletePrizeSuccess => ResourceManager.GetString("M_DeletePrizeSuccess", resourceCulture);
        public static string M_DeletePrizeTitle => ResourceManager.GetString("M_DeletePrizeTitle", resourceCulture);
        public static string M_FileLoaded => ResourceManager.GetString("M_FileLoaded", resourceCulture);
        public static string M_ImportSuccess => ResourceManager.GetString("M_ImportSuccess", resourceCulture);
        public static string M_KeepOneList => ResourceManager.GetString("M_KeepOneList", resourceCulture);
        public static string M_ListNameDialogPrimary_Add => ResourceManager.GetString("M_ListNameDialogPrimary_Add", resourceCulture);
        public static string M_ListNameDialogPrimary_Rename => ResourceManager.GetString("M_ListNameDialogPrimary_Rename", resourceCulture);
        public static string M_ListNameDialogTitle_Add => ResourceManager.GetString("M_ListNameDialogTitle_Add", resourceCulture);
        public static string M_ListNameDialogTitle_Rename => ResourceManager.GetString("M_ListNameDialogTitle_Rename", resourceCulture);
        public static string M_ListNameEmpty => ResourceManager.GetString("M_ListNameEmpty", resourceCulture);
        public static string M_ListNameExists => ResourceManager.GetString("M_ListNameExists", resourceCulture);
        public static string M_ListNameInvalid => ResourceManager.GetString("M_ListNameInvalid", resourceCulture);
        public static string M_ListNamePlaceholder => ResourceManager.GetString("M_ListNamePlaceholder", resourceCulture);
        public static string M_LoadFailed => ResourceManager.GetString("M_LoadFailed", resourceCulture);
        public static string M_OverwriteContent => ResourceManager.GetString("M_OverwriteContent", resourceCulture);
        public static string M_OverwritePrimary => ResourceManager.GetString("M_OverwritePrimary", resourceCulture);
        public static string M_OverwriteTitle => ResourceManager.GetString("M_OverwriteTitle", resourceCulture);
        public static string M_RenameListSuccess => ResourceManager.GetString("M_RenameListSuccess", resourceCulture);
        public static string M_SelectFileFirst => ResourceManager.GetString("M_SelectFileFirst", resourceCulture);
        public static string M_SelectListFirst => ResourceManager.GetString("M_SelectListFirst", resourceCulture);
        public static string M_SelectRequiredColumns => ResourceManager.GetString("M_SelectRequiredColumns", resourceCulture);
        public static string Page_Title => ResourceManager.GetString("Page_Title", resourceCulture);
        public static string S_CurrentList => ResourceManager.GetString("S_CurrentList", resourceCulture);
        public static string S_CurrentList_D => ResourceManager.GetString("S_CurrentList_D", resourceCulture);
    }
}
