#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the StronglyTypedResourceBuilder.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.FirstRunOobe;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
public class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal Resources() { }

    public static global::System.Resources.ResourceManager ResourceManager =>
        resourceMan ??= new global::System.Resources.ResourceManager("SecRandom.Langs.FirstRunOobe.Resources", typeof(Resources).Assembly);

    public static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    private static string Get(string name) => ResourceManager.GetString(name, resourceCulture) ?? string.Empty;

    public static string UserAgreement => Get(nameof(UserAgreement));
    public static string GplNotice => Get(nameof(GplNotice));
    public static string C_Title => Get(nameof(C_Title));
    public static string C_Intro => Get(nameof(C_Intro));
    public static string C_WelcomeTitle => Get(nameof(C_WelcomeTitle));
    public static string C_WelcomeDescription => Get(nameof(C_WelcomeDescription));
    public static string O_LanguageChinese => Get(nameof(O_LanguageChinese));
    public static string O_LanguageEnglish => Get(nameof(O_LanguageEnglish));
    public static string O_LanguageJapanese => Get(nameof(O_LanguageJapanese));
    public static string C_Language => Get(nameof(C_Language));
    public static string C_LegalTitle => Get(nameof(C_LegalTitle));
    public static string C_LegalDescription => Get(nameof(C_LegalDescription));
    public static string C_AgreementTitle => Get(nameof(C_AgreementTitle));
    public static string C_AgreementAccept => Get(nameof(C_AgreementAccept));
    public static string C_GplTitle => Get(nameof(C_GplTitle));
    public static string C_GplAccept => Get(nameof(C_GplAccept));
    public static string C_DataTitle => Get(nameof(C_DataTitle));
    public static string C_DataDescription => Get(nameof(C_DataDescription));
    public static string C_RestoreTitle => Get(nameof(C_RestoreTitle));
    public static string C_RestoreDescription => Get(nameof(C_RestoreDescription));
    public static string C_ImportSettings => Get(nameof(C_ImportSettings));
    public static string C_ImportAllData => Get(nameof(C_ImportAllData));
    public static string C_RollCallList => Get(nameof(C_RollCallList));
    public static string C_RollCallListDescription => Get(nameof(C_RollCallListDescription));
    public static string C_ImportRoster => Get(nameof(C_ImportRoster));
    public static string C_LotteryTitle => Get(nameof(C_LotteryTitle));
    public static string C_LotteryDescription => Get(nameof(C_LotteryDescription));
    public static string C_LotteryEnabled => Get(nameof(C_LotteryEnabled));
    public static string C_PrizeImport => Get(nameof(C_PrizeImport));
    public static string C_PrizeList => Get(nameof(C_PrizeList));
    public static string C_PrizeListDescription => Get(nameof(C_PrizeListDescription));
    public static string C_AppearanceTitle => Get(nameof(C_AppearanceTitle));
    public static string C_Theme => Get(nameof(C_Theme));
    public static string O_ThemeLight => Get(nameof(O_ThemeLight));
    public static string O_ThemeDark => Get(nameof(O_ThemeDark));
    public static string O_ThemeAuto => Get(nameof(O_ThemeAuto));
    public static string C_ThemeColor => Get(nameof(C_ThemeColor));
    public static string O_SystemColor => Get(nameof(O_SystemColor));
    public static string O_CustomColor => Get(nameof(O_CustomColor));
    public static string C_Opacity => Get(nameof(C_Opacity));
    public static string C_OpacityDescription => Get(nameof(C_OpacityDescription));
    public static string C_DesktopTitle => Get(nameof(C_DesktopTitle));
    public static string C_DesktopDescription => Get(nameof(C_DesktopDescription));
    public static string C_Autostart => Get(nameof(C_Autostart));
    public static string C_ShowStartupWindow => Get(nameof(C_ShowStartupWindow));
    public static string C_ShowStartupWindowDescription => Get(nameof(C_ShowStartupWindowDescription));
    public static string C_ExternalIntegration => Get(nameof(C_ExternalIntegration));
    public static string C_ExternalIntegrationDescription => Get(nameof(C_ExternalIntegrationDescription));
    public static string C_CompleteTitle => Get(nameof(C_CompleteTitle));
    public static string C_CompleteDescription => Get(nameof(C_CompleteDescription));
    public static string C_CompletedItems => Get(nameof(C_CompletedItems));
    public static string C_CompletedClass => Get(nameof(C_CompletedClass));
    public static string C_CompletedAppearance => Get(nameof(C_CompletedAppearance));
    public static string C_CompletedIntegration => Get(nameof(C_CompletedIntegration));
    public static string C_ResourcesTitle => Get(nameof(C_ResourcesTitle));
    public static string C_SectlWebsite => Get(nameof(C_SectlWebsite));
    public static string C_Documentation => Get(nameof(C_Documentation));
    public static string C_AuthorBilibili => Get(nameof(C_AuthorBilibili));
    public static string C_Sponsor => Get(nameof(C_Sponsor));
    public static string C_Community => Get(nameof(C_Community));
    public static string C_CommunityAnswer => Get(nameof(C_CommunityAnswer));
    public static string C_Previous => Get(nameof(C_Previous));
    public static string C_Start => Get(nameof(C_Start));
    public static string C_Next => Get(nameof(C_Next));
    public static string C_Finish => Get(nameof(C_Finish));
    public static string C_ImportSettingsTitle => Get(nameof(C_ImportSettingsTitle));
    public static string C_ImportAllDataTitle => Get(nameof(C_ImportAllDataTitle));
    public static string C_ImportTitle => Get(nameof(C_ImportTitle));
    public static string C_Import => Get(nameof(C_Import));
    public static string C_Cancel => Get(nameof(C_Cancel));
    public static string C_Close => Get(nameof(C_Close));
    public static string C_JsonFileType => Get(nameof(C_JsonFileType));
    public static string C_ZipFileType => Get(nameof(C_ZipFileType));
    public static string C_ExitTitle => Get(nameof(C_ExitTitle));
    public static string C_ExitDescription => Get(nameof(C_ExitDescription));
    public static string C_Exit => Get(nameof(C_Exit));
    public static string C_ContinueSetup => Get(nameof(C_ContinueSetup));
    public static string M_ImportConfirmation => Get(nameof(M_ImportConfirmation));
    public static string M_UnsupportedImportTitle => Get(nameof(M_UnsupportedImportTitle));
    public static string M_UnsupportedImport => Get(nameof(M_UnsupportedImport));
    public static string M_UnknownVersion => Get(nameof(M_UnknownVersion));
    public static string M_UnsupportedImportDetail => Get(nameof(M_UnsupportedImportDetail));
    public static string M_ImportCompleted => Get(nameof(M_ImportCompleted));
    public static string M_ImportFailed => Get(nameof(M_ImportFailed));
    public static string M_AgreementRequired => Get(nameof(M_AgreementRequired));
    public static string M_CompletionAgreementRequired => Get(nameof(M_CompletionAgreementRequired));
    public static string M_DesktopIntegrationFailed => Get(nameof(M_DesktopIntegrationFailed));
    public static string M_StudentsImported => Get(nameof(M_StudentsImported));
    public static string M_PrizesImported => Get(nameof(M_PrizesImported));
    public static string M_StepProgress => Get(nameof(M_StepProgress));
}
