//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.ListManagement.RollCallList {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.ListManagement.RollCallList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string C_Cancel => ResourceManager.GetString("C_Cancel", resourceCulture);
        public static string C_AddList => ResourceManager.GetString("C_AddList", resourceCulture);
        public static string C_ColumnMapping => ResourceManager.GetString("C_ColumnMapping", resourceCulture);
        public static string C_ColumnMapping_D => ResourceManager.GetString("C_ColumnMapping_D", resourceCulture);
        public static string C_DefaultListName => ResourceManager.GetString("C_DefaultListName", resourceCulture);
        public static string C_Exists => ResourceManager.GetString("C_Exists", resourceCulture);
        public static string C_FilePickerTitle => ResourceManager.GetString("C_FilePickerTitle", resourceCulture);
        public static string C_FilePickerTypeName => ResourceManager.GetString("C_FilePickerTypeName", resourceCulture);
        public static string C_Gender => ResourceManager.GetString("C_Gender", resourceCulture);
        public static string C_GenderColumn => ResourceManager.GetString("C_GenderColumn", resourceCulture);
        public static string C_Group => ResourceManager.GetString("C_Group", resourceCulture);
        public static string C_GroupColumn => ResourceManager.GetString("C_GroupColumn", resourceCulture);
        public static string C_Import => ResourceManager.GetString("C_Import", resourceCulture);
        public static string C_ImportList => ResourceManager.GetString("C_ImportList", resourceCulture);
        public static string C_ImportTitle => ResourceManager.GetString("C_ImportTitle", resourceCulture);
        public static string C_InfoMessage => ResourceManager.GetString("C_InfoMessage", resourceCulture);
        public static string C_InfoTitle => ResourceManager.GetString("C_InfoTitle", resourceCulture);
        public static string C_Name => ResourceManager.GetString("C_Name", resourceCulture);
        public static string C_NameColumn => ResourceManager.GetString("C_NameColumn", resourceCulture);
        public static string C_NoFileSelected => ResourceManager.GetString("C_NoFileSelected", resourceCulture);
        public static string C_NoneColumn => ResourceManager.GetString("C_NoneColumn", resourceCulture);
        public static string C_Refresh => ResourceManager.GetString("C_Refresh", resourceCulture);
        public static string C_RenameList => ResourceManager.GetString("C_RenameList", resourceCulture);
        public static string C_SelectFile => ResourceManager.GetString("C_SelectFile", resourceCulture);
        public static string C_SelectFileButton => ResourceManager.GetString("C_SelectFileButton", resourceCulture);
        public static string C_StudentId => ResourceManager.GetString("C_StudentId", resourceCulture);
        public static string C_StudentIdColumn => ResourceManager.GetString("C_StudentIdColumn", resourceCulture);
        public static string C_SupportedFormats => ResourceManager.GetString("C_SupportedFormats", resourceCulture);
        public static string C_Tags => ResourceManager.GetString("C_Tags", resourceCulture);
        public static string C_TagsColumn => ResourceManager.GetString("C_TagsColumn", resourceCulture);
        public static string C_TargetList => ResourceManager.GetString("C_TargetList", resourceCulture);
        public static string K_GenderColumns => ResourceManager.GetString("K_GenderColumns", resourceCulture);
        public static string K_GroupColumns => ResourceManager.GetString("K_GroupColumns", resourceCulture);
        public static string K_IdColumns => ResourceManager.GetString("K_IdColumns", resourceCulture);
        public static string K_NameColumns => ResourceManager.GetString("K_NameColumns", resourceCulture);
        public static string K_TagsColumns => ResourceManager.GetString("K_TagsColumns", resourceCulture);
        public static string M_DuplicateClose => ResourceManager.GetString("M_DuplicateClose", resourceCulture);
        public static string M_DuplicateContent => ResourceManager.GetString("M_DuplicateContent", resourceCulture);
        public static string M_DuplicatePrimary => ResourceManager.GetString("M_DuplicatePrimary", resourceCulture);
        public static string M_DuplicateTitle => ResourceManager.GetString("M_DuplicateTitle", resourceCulture);
        public static string M_FileLoaded => ResourceManager.GetString("M_FileLoaded", resourceCulture);
        public static string M_ImportSuccess => ResourceManager.GetString("M_ImportSuccess", resourceCulture);
        public static string M_AddListSuccess => ResourceManager.GetString("M_AddListSuccess", resourceCulture);
        public static string M_ListNameDialogPrimary_Add => ResourceManager.GetString("M_ListNameDialogPrimary_Add", resourceCulture);
        public static string M_ListNameDialogPrimary_Rename => ResourceManager.GetString("M_ListNameDialogPrimary_Rename", resourceCulture);
        public static string M_ListNameDialogTitle_Add => ResourceManager.GetString("M_ListNameDialogTitle_Add", resourceCulture);
        public static string M_ListNameDialogTitle_Rename => ResourceManager.GetString("M_ListNameDialogTitle_Rename", resourceCulture);
        public static string M_ListNameEmpty => ResourceManager.GetString("M_ListNameEmpty", resourceCulture);
        public static string M_ListNameExists => ResourceManager.GetString("M_ListNameExists", resourceCulture);
        public static string M_ListNameInvalid => ResourceManager.GetString("M_ListNameInvalid", resourceCulture);
        public static string M_ListNamePlaceholder => ResourceManager.GetString("M_ListNamePlaceholder", resourceCulture);
        public static string M_LoadFailed => ResourceManager.GetString("M_LoadFailed", resourceCulture);
        public static string M_OverwriteContent => ResourceManager.GetString("M_OverwriteContent", resourceCulture);
        public static string M_OverwritePrimary => ResourceManager.GetString("M_OverwritePrimary", resourceCulture);
        public static string M_OverwriteTitle => ResourceManager.GetString("M_OverwriteTitle", resourceCulture);
        public static string M_SelectFileFirst => ResourceManager.GetString("M_SelectFileFirst", resourceCulture);
        public static string M_SelectListFirst => ResourceManager.GetString("M_SelectListFirst", resourceCulture);
        public static string M_SelectRequiredColumns => ResourceManager.GetString("M_SelectRequiredColumns", resourceCulture);
        public static string M_RenameListSuccess => ResourceManager.GetString("M_RenameListSuccess", resourceCulture);
        public static string Page_Title => ResourceManager.GetString("Page_Title", resourceCulture);
        public static string S_CurrentList => ResourceManager.GetString("S_CurrentList", resourceCulture);
        public static string S_CurrentList_D => ResourceManager.GetString("S_CurrentList_D", resourceCulture);
    }
}
