//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace SecRandom.Langs.MainPages.FaceDraw;

public class Resources
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    public static global::System.Resources.ResourceManager ResourceManager =>
        resourceMan ??= new global::System.Resources.ResourceManager(
            "SecRandom.Langs.MainPages.FaceDraw.Resources", typeof(Resources).Assembly);

    public static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string C_Start => ResourceManager.GetString("C_Start", resourceCulture)!;
    public static string C_Stop => ResourceManager.GetString("C_Stop", resourceCulture)!;
    public static string M_Connecting => ResourceManager.GetString("M_Connecting", resourceCulture)!;
    public static string M_DetectorUnavailable => ResourceManager.GetString("M_DetectorUnavailable", resourceCulture)!;
    public static string M_FaceCountEmpty => ResourceManager.GetString("M_FaceCountEmpty", resourceCulture)!;
    public static string M_FaceCountFormat => ResourceManager.GetString("M_FaceCountFormat", resourceCulture)!;
    public static string M_NoFace => ResourceManager.GetString("M_NoFace", resourceCulture)!;
    public static string M_PickedFormat => ResourceManager.GetString("M_PickedFormat", resourceCulture)!;
    public static string M_Picking => ResourceManager.GetString("M_Picking", resourceCulture)!;
    public static string M_Ready => ResourceManager.GetString("M_Ready", resourceCulture)!;
    public static string M_Recognizing => ResourceManager.GetString("M_Recognizing", resourceCulture)!;
    public static string M_Starting => ResourceManager.GetString("M_Starting", resourceCulture)!;
    public static string M_Stopped => ResourceManager.GetString("M_Stopped", resourceCulture)!;
}
